/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio05_herencia;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author 6002755
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    DefaultListModel modelo;
    public Ventana() {
        initComponents();
        
        modelo = new DefaultListModel();
        jPanelEmpleado.setVisible(false);
        jPanelJubilado.setVisible(false);
        jButtonMostrar.setIcon(new ImageIcon("./ojo.png"));
        jList1.setModel(modelo);
        jLabelIcono.setIcon(new ImageIcon("./interfaz.png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEstado = new javax.swing.ButtonGroup();
        jLabelPersona = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jRadioButtonEmpleado = new javax.swing.JRadioButton();
        jRadioButtonJubilado = new javax.swing.JRadioButton();
        jLabelId = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jLabelDomicilio = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jPanelEmpleado = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelSueldo = new javax.swing.JLabel();
        jTextFieldSueldo = new javax.swing.JTextField();
        jLabelCargo = new javax.swing.JLabel();
        jTextFieldCargo = new javax.swing.JTextField();
        jPanelJubilado = new javax.swing.JPanel();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelSueldoJubi = new javax.swing.JLabel();
        jTextFieldSueldoJubi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldOcupacion = new javax.swing.JTextField();
        jButtonMostrar = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jLabelAut = new javax.swing.JLabel();
        jLabelInf = new javax.swing.JLabel();
        jLabelInsti = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLetra = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemJListFondo = new javax.swing.JMenuItem();
        jMenuItemJListLetra = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAutor = new javax.swing.JMenuItem();
        jMenuItemInstituto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personas");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jLabelPersona.setText("Estado de la persona:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        buttonGroupEstado.add(jRadioButtonEmpleado);
        jRadioButtonEmpleado.setText("Empleado");
        jRadioButtonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmpleadoActionPerformed(evt);
            }
        });

        buttonGroupEstado.add(jRadioButtonJubilado);
        jRadioButtonJubilado.setText("Jubilado");
        jRadioButtonJubilado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJubiladoActionPerformed(evt);
            }
        });

        jLabelId.setText("Id:");

        jLabelNombre.setText("Nombre:");

        jLabelDni.setText("DNI:");

        jLabelDomicilio.setText("Domicilio:");

        jLabelTelefono.setText("Teléfono:");

        jPanelEmpleado.setBackground(new java.awt.Color(204, 255, 255));

        jLabelCodigo.setText("Código:");

        jLabelSueldo.setText("Sueldo:");

        jLabelCargo.setText("Cargo:");

        javax.swing.GroupLayout jPanelEmpleadoLayout = new javax.swing.GroupLayout(jPanelEmpleado);
        jPanelEmpleado.setLayout(jPanelEmpleadoLayout);
        jPanelEmpleadoLayout.setHorizontalGroup(
            jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCargo)
                    .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabelSueldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                        .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                                .addComponent(jLabelCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelCargo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelEmpleadoLayout.setVerticalGroup(
            jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSueldo)
                    .addComponent(jTextFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelJubilado.setBackground(new java.awt.Color(204, 255, 204));

        jLabelEdad.setText("Edad:");

        jLabelSueldoJubi.setText("Sueldo:");

        jLabel1.setText("Ocupación:");

        javax.swing.GroupLayout jPanelJubiladoLayout = new javax.swing.GroupLayout(jPanelJubilado);
        jPanelJubilado.setLayout(jPanelJubiladoLayout);
        jPanelJubiladoLayout.setHorizontalGroup(
            jPanelJubiladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJubiladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJubiladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldOcupacion)
                    .addGroup(jPanelJubiladoLayout.createSequentialGroup()
                        .addComponent(jLabelSueldoJubi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSueldoJubi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJubiladoLayout.createSequentialGroup()
                        .addGroup(jPanelJubiladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJubiladoLayout.createSequentialGroup()
                                .addComponent(jLabelEdad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelJubiladoLayout.setVerticalGroup(
            jPanelJubiladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJubiladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJubiladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdad)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelJubiladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSueldoJubi)
                    .addComponent(jTextFieldSueldoJubi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jLabelAut.setText("Ctrl+A  --  Autor");

        jLabelInf.setText("Información:");

        jLabelInsti.setText("Ctrl+I  --  Instituto");

        jMenu1.setText("Colores");

        jMenuItemLetra.setText("Color de letra");
        jMenuItemLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLetraActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLetra);

        jMenu3.setText("Lista");

        jMenuItemJListFondo.setText("Fondo");
        jMenuItemJListFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJListFondoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemJListFondo);

        jMenuItemJListLetra.setText("Letra");
        jMenuItemJListLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJListLetraActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemJListLetra);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Información");

        jMenuItemAutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAutor.setText("Autor");
        jMenuItemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAutor);

        jMenuItemInstituto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemInstituto.setText("Instituto");
        jMenuItemInstituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInstitutoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemInstituto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDni)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelDomicilio)
                            .addComponent(jLabelTelefono)
                            .addComponent(jLabelId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldId)
                            .addComponent(jTextFieldDni)
                            .addComponent(jTextFieldDomicilio)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelJubilado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPersona)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonJubilado)
                        .addGap(90, 90, 90)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAut)
                    .addComponent(jLabelInsti)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInf)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelInf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelAut)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelInsti)
                            .addGap(12, 12, 12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPersona)
                            .addComponent(jRadioButtonEmpleado)
                            .addComponent(jRadioButtonJubilado))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelJubilado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDni)
                            .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDomicilio)
                            .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelefono)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        if (!comprobarCampos()){
            JOptionPane.showMessageDialog(this, "Tiene algún campo sin completar.");
            return;
            
        }
        try{
            if (jRadioButtonEmpleado.isSelected()){

                int codigo = Integer.parseInt(jTextFieldCodigo.getText());
                String cargo = jTextFieldCargo.getText();
                double sueldo = Double.parseDouble(jTextFieldSueldo.getText());
                int id = Integer.parseInt(jTextFieldId.getText());
                String nombre = jTextFieldNombre.getText();
                String dni = jTextFieldDni.getText();
                String domicilio = jTextFieldDomicilio.getText();
                String telefono = jTextFieldTelefono.getText();
                Empleado emp = new Empleado(codigo, cargo, sueldo, id, nombre, dni, domicilio, telefono);
                modelo.addElement(emp.toString());
                jList1.setModel(modelo);
            }
            if (jRadioButtonJubilado.isSelected()){
                int edad = Integer.parseInt(jTextFieldEdad.getText());
                String ocupacion = jTextFieldOcupacion.getText();
                double sueldo = Double.parseDouble(jTextFieldSueldoJubi.getText());
                int id = Integer.parseInt(jTextFieldId.getText());
                String nombre = jTextFieldNombre.getText();
                String dni = jTextFieldDni.getText();
                String domicilio = jTextFieldDomicilio.getText();
                String telefono = jTextFieldTelefono.getText();
                Jubilado jub = new Jubilado(sueldo, ocupacion, edad, id, nombre, dni, domicilio, telefono);
                modelo.addElement(jub.toString());
                jList1.setModel(modelo);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Ha habido algún error de entrada de datos.");
        }
        
        
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jMenuItemJListFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJListFondoActionPerformed
        Color c = JColorChooser.showDialog(this, "Selecciona color de fondo", Color.yellow);
        jList1.setBackground(c);
    }//GEN-LAST:event_jMenuItemJListFondoActionPerformed

    private void jMenuItemJListLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJListLetraActionPerformed
        Color c = JColorChooser.showDialog(this, "Selecciona color de letra", Color.yellow);
        jList1.setForeground(c);
    }//GEN-LAST:event_jMenuItemJListLetraActionPerformed

    private void jMenuItemLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLetraActionPerformed
        Color c = JColorChooser.showDialog(this, "Selecciona color de letra.", Color.yellow);
        jLabelCargo.setForeground(c);
        jLabel1.setForeground(c);
        jLabelCodigo.setForeground(c);
        jLabelDni.setForeground(c);
        jLabelDomicilio.setForeground(c);
        jLabelEdad.setForeground(c);
        jLabelNombre.setForeground(c);
        jLabelId.setForeground(c);
        jLabelPersona.setForeground(c);
        jLabelSueldo.setForeground(c);
        jLabelSueldoJubi.setForeground(c);
        jLabelTelefono.setForeground(c);
        jRadioButtonEmpleado.setForeground(c);
        jRadioButtonJubilado.setForeground(c);
        jLabelAut.setForeground(c);
        jLabelInf.setForeground(c);
        jLabelInsti.setForeground(c);
        
    }//GEN-LAST:event_jMenuItemLetraActionPerformed

    private void jMenuItemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutorActionPerformed
        String mensaje = "Esta aplicación ha sido creada por\nDavid Carro Salinas\nAlumno del Ciclo Superior de \nDesarrollo de Aplicaciones Multiplataforma";
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jMenuItemAutorActionPerformed

    private void jMenuItemInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstitutoActionPerformed
        String mensaje = "I.E.S. Venancio Blanco\nC/Filipinas, 33, 37003\nSalamanca\nwww.iesvenancioblanco.es";
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jMenuItemInstitutoActionPerformed

    private void jRadioButtonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmpleadoActionPerformed
        jPanelJubilado.setVisible(false);
        jPanelEmpleado.setVisible(true);
    }//GEN-LAST:event_jRadioButtonEmpleadoActionPerformed

    private void jRadioButtonJubiladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJubiladoActionPerformed
        jPanelJubilado.setVisible(true);
        jPanelEmpleado.setVisible(false);
    }//GEN-LAST:event_jRadioButtonJubiladoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupEstado;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAut;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelInf;
    private javax.swing.JLabel jLabelInsti;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPersona;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelSueldoJubi;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAutor;
    private javax.swing.JMenuItem jMenuItemInstituto;
    private javax.swing.JMenuItem jMenuItemJListFondo;
    private javax.swing.JMenuItem jMenuItemJListLetra;
    private javax.swing.JMenuItem jMenuItemLetra;
    private javax.swing.JPanel jPanelEmpleado;
    private javax.swing.JPanel jPanelJubilado;
    private javax.swing.JRadioButton jRadioButtonEmpleado;
    private javax.swing.JRadioButton jRadioButtonJubilado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldOcupacion;
    private javax.swing.JTextField jTextFieldSueldo;
    private javax.swing.JTextField jTextFieldSueldoJubi;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    private boolean comprobarCampos() {
        boolean llenos = true;
        if (jTextFieldId.getText().isEmpty())
            llenos = false;
        if (jTextFieldNombre.getText().isEmpty())
            llenos = false;
        if (jTextFieldDni.getText().isEmpty())
            llenos = false;
        if (jTextFieldDomicilio.getText().isEmpty())
            llenos = false;
        if (jTextFieldTelefono.getText().isEmpty())
            llenos = false;
        
        if (jRadioButtonEmpleado.isSelected()){
            if (jTextFieldCodigo.getText().isEmpty())
                llenos = false;
            if (jTextFieldSueldo.getText().isEmpty())
            llenos = false;
            if (jTextFieldCargo.getText().isEmpty())
            llenos = false;
        }
        if (jRadioButtonJubilado.isSelected()){
            if (jTextFieldEdad.getText().isEmpty())
                llenos = false;
            if (jTextFieldSueldoJubi.getText().isEmpty())
            llenos = false;
            if (jTextFieldOcupacion.getText().isEmpty())
            llenos = false;
        }
        
        return llenos;
        
    }
}
