/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jradiobutton;

/**
 *
 * @author 6002755
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_colores = new javax.swing.ButtonGroup();
        jRadioButton_rojo = new javax.swing.JRadioButton();
        jRadioButton_amarillo = new javax.swing.JRadioButton();
        jRadioButton_verde = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField_salida = new javax.swing.JTextField();
        jComboBox_colores = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel_texto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup_colores.add(jRadioButton_rojo);
        jRadioButton_rojo.setText("Rojo");

        buttonGroup_colores.add(jRadioButton_amarillo);
        jRadioButton_amarillo.setText("Amarillo");

        buttonGroup_colores.add(jRadioButton_verde);
        jRadioButton_verde.setText("Verde");

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_salida.setText(" ");

        jComboBox_colores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Amarillo", "Verde", "Negro" }));
        jComboBox_colores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_coloresItemStateChanged(evt);
            }
        });
        jComboBox_colores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_coloresActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(14, 10, 40, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel_texto.setText("Texto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_verde)
                    .addComponent(jRadioButton_amarillo)
                    .addComponent(jRadioButton_rojo)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_colores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(jLabel_texto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton_rojo)
                        .addGap(22, 22, 22)
                        .addComponent(jRadioButton_amarillo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_verde))
                    .addComponent(jTextField_salida))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox_colores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_texto))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton_rojo.isSelected()){
            jTextField_salida.setBackground(java.awt.Color.RED);
        }
        else if (jRadioButton_amarillo.isSelected()){
            jTextField_salida.setBackground(java.awt.Color.YELLOW);
        }
        else if (jRadioButton_verde.isSelected()){
            jTextField_salida.setBackground(java.awt.Color.GREEN);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_coloresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_coloresItemStateChanged

    }//GEN-LAST:event_jComboBox_coloresItemStateChanged

    private void jComboBox_coloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_coloresActionPerformed
        // TODO add your handling code here:
        int pos = jComboBox_colores.getSelectedIndex();
        switch (pos){
            case 0:
                jTextField_salida.setBackground(java.awt.Color.RED);
                break;
            case 1:
                jTextField_salida.setBackground(java.awt.Color.YELLOW);
                break;
            case 2:
                jTextField_salida.setBackground(java.awt.Color.GREEN);
                break;
            case 3:
                jTextField_salida.setBackground(java.awt.Color.BLACK);
                break;
            
        }
    }//GEN-LAST:event_jComboBox_coloresActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        String valor = (String) jSpinner1.getValue();
        jLabel_texto.setText(valor); 
    }//GEN-LAST:event_jSpinner1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_colores;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_colores;
    private javax.swing.JLabel jLabel_texto;
    private javax.swing.JRadioButton jRadioButton_amarillo;
    private javax.swing.JRadioButton jRadioButton_rojo;
    private javax.swing.JRadioButton jRadioButton_verde;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField_salida;
    // End of variables declaration//GEN-END:variables
}
