package entidades;
// Generated 14 dic. 2023 18:03:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Auxdept generated by hbm2java
 */
public class Auxdept  implements java.io.Serializable {


     private int deptNo;
     private String dnombre;
     private String loc;
     private Set auxemps = new HashSet(0);

    public Auxdept() {
    }

	
    public Auxdept(int deptNo) {
        this.deptNo = deptNo;
    }
    public Auxdept(int deptNo, String dnombre, String loc, Set auxemps) {
       this.deptNo = deptNo;
       this.dnombre = dnombre;
       this.loc = loc;
       this.auxemps = auxemps;
    }
   
    public int getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(int deptNo) {
        this.deptNo = deptNo;
    }
    public String getDnombre() {
        return this.dnombre;
    }
    
    public void setDnombre(String dnombre) {
        this.dnombre = dnombre;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
    public Set getAuxemps() {
        return this.auxemps;
    }
    
    public void setAuxemps(Set auxemps) {
        this.auxemps = auxemps;
    }




}


