/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.formulariodatos;

/**
 *
 * @author 6002755
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        
        initComponents();
        jPanel_ocultar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_curso = new javax.swing.ButtonGroup();
        jLabel_datos = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel_curso = new javax.swing.JLabel();
        jRadioButton_1 = new javax.swing.JRadioButton();
        jRadioButton_2 = new javax.swing.JRadioButton();
        jRadioButton_3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_texto = new javax.swing.JTextArea();
        jButton_limpiar = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel_ocultar = new javax.swing.JPanel();
        jLabel_datos2 = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_fecha = new javax.swing.JSpinner();
        jSpinner_edad = new javax.swing.JSpinner();
        jComboBox_provincias = new javax.swing.JComboBox<>();
        jButton_imprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_ciclo = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_datos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_datos.setForeground(new java.awt.Color(51, 0, 255));
        jLabel_datos.setText("DATOS ALUMNOS");

        jLabel_nombre.setText("Nombre del Alumno");

        jLabel_curso.setText("Curso:");

        buttonGroup_curso.add(jRadioButton_1);
        jRadioButton_1.setText("1º");

        buttonGroup_curso.add(jRadioButton_2);
        jRadioButton_2.setText("2º");

        buttonGroup_curso.add(jRadioButton_3);
        jRadioButton_3.setText("3º");

        jTextArea_texto.setColumns(20);
        jTextArea_texto.setRows(5);
        jScrollPane1.setViewportView(jTextArea_texto);

        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Ver/Ocultar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jPanel_ocultar.setEnabled(false);

        jLabel_datos2.setText("Datos Personales");

        jLabel_fecha.setText("Fecha nacimiento:");

        jLabel1.setText("Edad:");

        jLabel2.setText("Provincia:");

        jSpinner_fecha.setModel(new javax.swing.SpinnerDateModel());

        jSpinner_edad.setModel(new javax.swing.SpinnerNumberModel(16, null, null, 1));

        jComboBox_provincias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salamanca", "Ávila", "Segovia", "Valladolid", "León", "Zamora", "Soria", "Burgos" }));

        javax.swing.GroupLayout jPanel_ocultarLayout = new javax.swing.GroupLayout(jPanel_ocultar);
        jPanel_ocultar.setLayout(jPanel_ocultarLayout);
        jPanel_ocultarLayout.setHorizontalGroup(
            jPanel_ocultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ocultarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_ocultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel_ocultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_fecha)
                        .addComponent(jLabel_datos2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ocultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_provincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel_ocultarLayout.setVerticalGroup(
            jPanel_ocultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ocultarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_datos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ocultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fecha)
                    .addComponent(jSpinner_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ocultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ocultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_provincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jButton_imprimir.setForeground(new java.awt.Color(255, 0, 51));
        jButton_imprimir.setText("IMPRIMIR");
        jButton_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imprimirActionPerformed(evt);
            }
        });

        jLabel3.setText("Ciclo Formativo:");

        jComboBox_ciclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un ciclo", "DAM", "DAW", "ASIR", "SMR" }));

        jCheckBox1.setText("Matriculado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jRadioButton_1)
                                                .addComponent(jRadioButton_2)
                                                .addComponent(jRadioButton_3))
                                            .addComponent(jButton_limpiar)))
                                    .addComponent(jLabel_curso))
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_ocultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_nombre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel_datos)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_ocultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_curso)
                            .addComponent(jRadioButton_1))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_3)
                        .addGap(12, 12, 12)
                        .addComponent(jButton_limpiar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        jPanel_ocultar.setBackground(java.awt.Color.GRAY);
        if (jToggleButton1.isSelected())
            jPanel_ocultar.setVisible(true);
        else
            jPanel_ocultar.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed

        // TODO add your handling code here:
        buttonGroup_curso.clearSelection();
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imprimirActionPerformed
        // TODO add your handling code here:
        jTextArea_texto.setText("");
        
        jTextArea_texto.append("\nNombre: " + jTextField_nombre.getText());
        
        if (jRadioButton_1.isSelected())
            jTextArea_texto.append("\nCurso: 1º");
        else if (jRadioButton_2.isSelected())
            jTextArea_texto.append("\nCurso: 2º");
        else if (jRadioButton_3.isSelected())
            jTextArea_texto.append("\nCurso: 3º");
        
        switch (jComboBox_ciclo.getSelectedIndex()){
            case 0:
                jTextArea_texto.append("\nCiclo formativo: " );
                break;
            case 1:
                jTextArea_texto.append("\nCiclo formativo: DAM" );
                break;
            case 2:
                jTextArea_texto.append("\nCiclo formativo: DAW" );
                break;
            case 3:
                jTextArea_texto.append("\nCiclo formativo: ASIR" );
                break;
            case 4:
                jTextArea_texto.append("\nCiclo formativo: SMR" );
                break;
        }
        if (jCheckBox1.isSelected())
            jTextArea_texto.append("\nMatriculado: Si");
        else
            jTextArea_texto.append("\nMatriculado: No");
        
        jTextArea_texto.append("\nFecha de nacimiento: " + jSpinner_fecha.getValue() );
        
        jTextArea_texto.append("\nEdad:: " + jSpinner_edad.getValue() );
        
         switch (jComboBox_provincias.getSelectedIndex()){
            case 0:
                jTextArea_texto.append("\nProvincia: Salamanca" );
                break;
            case 1:
                jTextArea_texto.append("\nProvincia: Ávila" );
                break;
            case 2:
                jTextArea_texto.append("\nCiclo formativo: Segovia" );
                break;
            case 3:
                jTextArea_texto.append("\nCiclo formativo: Valladolid" );
                break;
            case 4:
                jTextArea_texto.append("\nCiclo formativo: León" );
                break;
            case 5:
                jTextArea_texto.append("\nCiclo formativo: Zamora" );
                break;
            case 6:
                jTextArea_texto.append("\nCiclo formativo: Soria" );
                break;
            case 7:
                jTextArea_texto.append("\nCiclo formativo: Burgos" );
                break;
            
        }
        
        
        
        
                
        
    }//GEN-LAST:event_jButton_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_curso;
    private javax.swing.JButton jButton_imprimir;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox_ciclo;
    private javax.swing.JComboBox<String> jComboBox_provincias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JLabel jLabel_datos;
    private javax.swing.JLabel jLabel_datos2;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JPanel jPanel_ocultar;
    private javax.swing.JRadioButton jRadioButton_1;
    private javax.swing.JRadioButton jRadioButton_2;
    private javax.swing.JRadioButton jRadioButton_3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_edad;
    private javax.swing.JSpinner jSpinner_fecha;
    private javax.swing.JTextArea jTextArea_texto;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
