/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio1componentes_davidcarrosalinas;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JRadioButton;

/**
 *
 * @author 6002755
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    static String[] categorias = {"Drama", "Comedia", "Ciencia Ficción", "Terror", "Thriller", "Suspense", "Fantástica", "Animada"};
    
    public Ventana() {
        
        initComponents();
        
        jButton_icono.setIcon(new ImageIcon("./icono.png"));
        jPanel_anadir.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_edades = new javax.swing.ButtonGroup();
        jLabel_peli = new javax.swing.JLabel();
        jTextField_director = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_director = new javax.swing.JLabel();
        jRadioButton_edad6 = new javax.swing.JRadioButton();
        jLabel_edad = new javax.swing.JLabel();
        jRadioButton_edad12 = new javax.swing.JRadioButton();
        jRadioButton_edad16 = new javax.swing.JRadioButton();
        jRadioButton_edad18 = new javax.swing.JRadioButton();
        jRadioButton_todos = new javax.swing.JRadioButton();
        jLabel_durac = new javax.swing.JLabel();
        jSpinner_durac = new javax.swing.JSpinner();
        jLabel_cat = new javax.swing.JLabel();
        jComboBox_categorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel_pais = new javax.swing.JLabel();
        jCheckBox_correcto = new javax.swing.JCheckBox();
        jToggleButton_recom = new javax.swing.JToggleButton();
        jPanel_anadir = new javax.swing.JPanel();
        jButton_anadir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_infor = new javax.swing.JTextArea();
        jButton_fondo = new javax.swing.JButton();
        jButton_texto = new javax.swing.JButton();
        jLabel_texto = new javax.swing.JLabel();
        jButton_icono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Películas");
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel_peli.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel_peli.setForeground(new java.awt.Color(153, 102, 255));
        jLabel_peli.setText("Películas");
        jLabel_peli.setToolTipText("");

        jTextField_director.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jLabel_nombre.setText("Nombre:");

        jLabel_director.setText("Director:");

        buttonGroup_edades.add(jRadioButton_edad6);
        jRadioButton_edad6.setText("6");

        jLabel_edad.setText("Para mayores de:");

        buttonGroup_edades.add(jRadioButton_edad12);
        jRadioButton_edad12.setText("12");

        buttonGroup_edades.add(jRadioButton_edad16);
        jRadioButton_edad16.setText("16");

        buttonGroup_edades.add(jRadioButton_edad18);
        jRadioButton_edad18.setText("18");

        buttonGroup_edades.add(jRadioButton_todos);
        jRadioButton_todos.setText("Todos los públicos");

        jLabel_durac.setText("Duración:");

        jSpinner_durac.setModel(new javax.swing.SpinnerNumberModel(120, null, null, 5));

        jLabel_cat.setText("Categoría:");

        jComboBox_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drama", "Comedia", "Ciencia Ficción", "Terror", "Thriller", "Suspense", "Fantástica", "Animada" }));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "EEUU", "Japón", "China", "India", "Francia", "España", "Alemania", "Inglaterra", "Noruega" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setVisibleRowCount(4);
        jScrollPane1.setViewportView(jList1);

        jLabel_pais.setText("País:");

        jCheckBox_correcto.setText("He revisado los campos y confirmo que están correctos.");
        jCheckBox_correcto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_correctoActionPerformed(evt);
            }
        });

        jToggleButton_recom.setText("Recomendable");

        jButton_anadir.setText("Añadir");
        jButton_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_anadirLayout = new javax.swing.GroupLayout(jPanel_anadir);
        jPanel_anadir.setLayout(jPanel_anadirLayout);
        jPanel_anadirLayout.setHorizontalGroup(
            jPanel_anadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_anadir)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel_anadirLayout.setVerticalGroup(
            jPanel_anadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton_anadir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTextArea_infor.setColumns(20);
        jTextArea_infor.setRows(5);
        jScrollPane2.setViewportView(jTextArea_infor);

        jButton_fondo.setText("Fondo");
        jButton_fondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fondoActionPerformed(evt);
            }
        });

        jButton_texto.setText("Texto");
        jButton_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_textoActionPerformed(evt);
            }
        });

        jLabel_texto.setText("Color del área:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombre))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_director)
                            .addComponent(jTextField_director, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_durac)
                            .addComponent(jSpinner_durac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_edad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_pais)
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton_recom)
                        .addGap(0, 420, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_fondo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_texto))
                                    .addComponent(jLabel_texto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel_cat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBox_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton_edad6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton_edad12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton_edad16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton_edad18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton_todos)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox_correcto, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(jPanel_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)))
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel_peli)
                .addGap(18, 18, 18)
                .addComponent(jButton_icono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_peli))
                    .addComponent(jButton_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(jLabel_director)
                    .addComponent(jLabel_durac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner_durac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_edad)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton_edad6)
                                    .addComponent(jRadioButton_edad12)
                                    .addComponent(jRadioButton_edad16)
                                    .addComponent(jRadioButton_edad18)
                                    .addComponent(jRadioButton_todos))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_cat)
                                    .addComponent(jComboBox_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel_pais))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jToggleButton_recom)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_correcto)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jPanel_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_texto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_fondo)
                            .addComponent(jButton_texto))
                        .addGap(49, 49, 49))))
        );

        jTextField_director.getAccessibleContext().setAccessibleDescription("Nombre");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jButton_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anadirActionPerformed
        // TODO add your handling code here:
        String infor = "Información de la película:";
        infor += "\nTítulo:\t\t" + jTextField_nombre.getText();
        infor += "\nDirector:\t\t" + jTextField_director.getText();
        infor += "\nDuración:\t\t" + jSpinner_durac.getValue();        
        String edad = "";
        if (jRadioButton_edad6.isSelected())
            edad = "6";
        else if (jRadioButton_edad12.isSelected())
            edad = "12";
        else if (jRadioButton_edad18.isSelected())
            edad = "18";
        else if (jRadioButton_edad16.isSelected())
            edad = "16";
        else if (jRadioButton_todos.isSelected())
            edad = "Para todos los públicos";
        
        infor += "\nRestricción de edad:\t" + edad ;
        infor += "\nCategoría:\t\t" + categorias[jComboBox_categorias.getSelectedIndex()];
        infor += "\nPais:\t\t" + jList1.getSelectedValue() ;
        if (jToggleButton_recom.isSelected())
            infor += "\nRecomendada:\tSi.";
        else 
            infor += "\nRecomendada:\tNo.";
                
        
        
        jTextArea_infor.setText(infor);
        
    }//GEN-LAST:event_jButton_anadirActionPerformed

    private void jCheckBox_correctoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_correctoActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_correcto.isSelected())
            jPanel_anadir.setVisible(true);
        else
            jPanel_anadir.setVisible(false);
            
    }//GEN-LAST:event_jCheckBox_correctoActionPerformed

    private void jButton_fondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fondoActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(this, "Selecciona color de fondo", Color.yellow);
        jTextArea_infor.setBackground(c);
        
    }//GEN-LAST:event_jButton_fondoActionPerformed

    private void jButton_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_textoActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(this, "Selecciona color de fondo", Color.yellow);
        jTextArea_infor.setForeground(c);
    }//GEN-LAST:event_jButton_textoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Ventana().setVisible(true);
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_edades;
    private javax.swing.JButton jButton_anadir;
    private javax.swing.JButton jButton_fondo;
    private javax.swing.JButton jButton_icono;
    private javax.swing.JButton jButton_texto;
    private javax.swing.JCheckBox jCheckBox_correcto;
    private javax.swing.JComboBox<String> jComboBox_categorias;
    private javax.swing.JLabel jLabel_cat;
    private javax.swing.JLabel jLabel_director;
    private javax.swing.JLabel jLabel_durac;
    private javax.swing.JLabel jLabel_edad;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_pais;
    private javax.swing.JLabel jLabel_peli;
    private javax.swing.JLabel jLabel_texto;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel_anadir;
    private javax.swing.JRadioButton jRadioButton_edad12;
    private javax.swing.JRadioButton jRadioButton_edad16;
    private javax.swing.JRadioButton jRadioButton_edad18;
    private javax.swing.JRadioButton jRadioButton_edad6;
    private javax.swing.JRadioButton jRadioButton_todos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_durac;
    private javax.swing.JTextArea jTextArea_infor;
    private javax.swing.JTextField jTextField_director;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JToggleButton jToggleButton_recom;
    // End of variables declaration//GEN-END:variables
}
