/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio06_clubfutbol;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 6002755
 */
public class GestionClub extends javax.swing.JFrame {

    /**
     * Creates new form GestionClub
     */
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private DefaultListModel modelo;
    
    public GestionClub() {
        initComponents();
        modelo = new DefaultListModel();
        modelo.clear();
        jList1.setModel(modelo);
        setIconImage(new ImageIcon("favicon.png").getImage());
        jPanelDirectivo.setBackground(new Color(254, 195, 195));
        jPanelEntrenador.setBackground(new Color(223, 254, 195));
        jPanelJugador.setBackground(new Color(195, 254, 236));
        jPanelMantenedor.setBackground(new Color(254, 195, 241));
        jMenuBar1.setBackground(new Color(196, 196, 196));
        jList1.setBackground(new Color(252, 255, 212));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPosicion = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelEntrenador = new javax.swing.JPanel();
        jTextFieldNombreEntre = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jTextFieldDniEntre = new javax.swing.JTextField();
        jTextFieldDireccEntre = new javax.swing.JTextField();
        jTextFieldTelefEntre = new javax.swing.JTextField();
        jTextFieldPartidosEntre = new javax.swing.JTextField();
        jLabelDni1 = new javax.swing.JLabel();
        jLabelDirecc1 = new javax.swing.JLabel();
        jLabelTelef1 = new javax.swing.JLabel();
        jLabelPart1 = new javax.swing.JLabel();
        jLabelSueldoEntre = new javax.swing.JLabel();
        jTextFieldSueldoEntre = new javax.swing.JTextField();
        jLabelPlusEntre = new javax.swing.JLabel();
        jTextFieldPlusEntre = new javax.swing.JTextField();
        jPanelJugador = new javax.swing.JPanel();
        jTextFieldNombreJuga = new javax.swing.JTextField();
        jLabelNombre2 = new javax.swing.JLabel();
        jTextFieldDniJuga = new javax.swing.JTextField();
        jTextFieldDireccJuga = new javax.swing.JTextField();
        jTextFieldTelefJuga = new javax.swing.JTextField();
        jTextFieldPartidosJuga = new javax.swing.JTextField();
        jLabelDni2 = new javax.swing.JLabel();
        jLabelDirecc2 = new javax.swing.JLabel();
        jLabelTelef2 = new javax.swing.JLabel();
        jLabelPart2 = new javax.swing.JLabel();
        jLabelSueldoJuga = new javax.swing.JLabel();
        jLabelNacimientoJuga = new javax.swing.JLabel();
        jLabelPlusPartJuga = new javax.swing.JLabel();
        jLabelGolesJuga = new javax.swing.JLabel();
        jLabelPlusGolJuga = new javax.swing.JLabel();
        jTextFieldSueldoJuga = new javax.swing.JTextField();
        jTextFieldPluspartJuga = new javax.swing.JTextField();
        jTextFieldGolesJuga = new javax.swing.JTextField();
        jTextFieldPlusGolJuga = new javax.swing.JTextField();
        jLabelPosicionJuga = new javax.swing.JLabel();
        jRadioButtonPortero = new javax.swing.JRadioButton();
        jRadioButtonDefensa = new javax.swing.JRadioButton();
        jRadioButtonDelantero = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();
        jPanelDirectivo = new javax.swing.JPanel();
        jTextFieldNombreDirect = new javax.swing.JTextField();
        jLabelNombre3 = new javax.swing.JLabel();
        jTextFieldDniDirect = new javax.swing.JTextField();
        jTextFieldDireccDirect = new javax.swing.JTextField();
        jTextFieldTelefDirect = new javax.swing.JTextField();
        jTextFieldPartidosDirect = new javax.swing.JTextField();
        jLabelDni3 = new javax.swing.JLabel();
        jLabelDirecc3 = new javax.swing.JLabel();
        jLabelTelef3 = new javax.swing.JLabel();
        jLabelPart3 = new javax.swing.JLabel();
        jLabelSueldoDirect = new javax.swing.JLabel();
        jLabelActivoDirect = new javax.swing.JLabel();
        jComboBoxActivoDirect = new javax.swing.JComboBox<>();
        jTextFieldSueldoDirect = new javax.swing.JTextField();
        jRadioButtonPresidente = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonDelegado = new javax.swing.JRadioButton();
        jRadioButtonSecretario = new javax.swing.JRadioButton();
        jPanelMantenedor = new javax.swing.JPanel();
        jTextFieldNombreMant = new javax.swing.JTextField();
        jLabelNombre4 = new javax.swing.JLabel();
        jTextFieldDniMant = new javax.swing.JTextField();
        jTextFieldDireccMant = new javax.swing.JTextField();
        jTextFieldTelefMant = new javax.swing.JTextField();
        jTextFieldPartidosMant = new javax.swing.JTextField();
        jLabelDni4 = new javax.swing.JLabel();
        jLabelDirecc4 = new javax.swing.JLabel();
        jLabelTelef4 = new javax.swing.JLabel();
        jLabelPart4 = new javax.swing.JLabel();
        jTextFieldSueldoMant = new javax.swing.JTextField();
        jLabelFijoMant = new javax.swing.JLabel();
        jLabelSueldoMant = new javax.swing.JLabel();
        jComboBoxFijoMant = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAnadir = new javax.swing.JMenuItem();
        jMenuItemBorrar = new javax.swing.JMenuItem();
        jMenuItemVaciar = new javax.swing.JMenuItem();
        jMenuItemLlenar = new javax.swing.JMenuItem();
        jMenuGuarda_Importa = new javax.swing.JMenu();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemImportar = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuItemAutor = new javax.swing.JMenuItem();
        jMenuItemInstituto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestionClub");

        jLabelNombre1.setText("Nombre:");

        jTextFieldTelefEntre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefEntreFocusLost(evt);
            }
        });

        jTextFieldPartidosEntre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPartidosEntreFocusLost(evt);
            }
        });

        jLabelDni1.setText("DNI:");

        jLabelDirecc1.setText("Direción:");

        jLabelTelef1.setText("Teléfono:");

        jLabelPart1.setText("Partidos ganados:");

        jLabelSueldoEntre.setText("Sueldo:");

        jTextFieldSueldoEntre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSueldoEntreFocusLost(evt);
            }
        });

        jLabelPlusEntre.setText("Plus partido:");

        jTextFieldPlusEntre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPlusEntreFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelEntrenadorLayout = new javax.swing.GroupLayout(jPanelEntrenador);
        jPanelEntrenador.setLayout(jPanelEntrenadorLayout);
        jPanelEntrenadorLayout.setHorizontalGroup(
            jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntrenadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombre1)
                    .addComponent(jLabelDni1)
                    .addComponent(jLabelDirecc1)
                    .addComponent(jLabelTelef1)
                    .addComponent(jLabelPart1))
                .addGap(18, 18, 18)
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombreEntre)
                    .addComponent(jTextFieldPartidosEntre)
                    .addComponent(jTextFieldTelefEntre)
                    .addComponent(jTextFieldDireccEntre)
                    .addComponent(jTextFieldDniEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSueldoEntre)
                    .addComponent(jLabelPlusEntre))
                .addGap(18, 18, 18)
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSueldoEntre)
                    .addComponent(jTextFieldPlusEntre, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanelEntrenadorLayout.setVerticalGroup(
            jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntrenadorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre1)
                    .addComponent(jLabelSueldoEntre)
                    .addComponent(jTextFieldSueldoEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDniEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDni1)
                    .addComponent(jLabelPlusEntre)
                    .addComponent(jTextFieldPlusEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDirecc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelef1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPartidosEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPart1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTextFieldNombreEntre.getAccessibleContext().setAccessibleDescription("Nombre");

        jTabbedPane1.addTab("Entrenadores", jPanelEntrenador);

        jLabelNombre2.setText("Nombre:");

        jTextFieldTelefJuga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefJugaFocusLost(evt);
            }
        });

        jTextFieldPartidosJuga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPartidosJugaFocusLost(evt);
            }
        });

        jLabelDni2.setText("DNI:");

        jLabelDirecc2.setText("Direción:");

        jLabelTelef2.setText("Teléfono:");

        jLabelPart2.setText("Partidos ganados:");

        jLabelSueldoJuga.setText("Sueldo:");

        jLabelNacimientoJuga.setText("F. Nacimiento:");

        jLabelPlusPartJuga.setText("Plus partido:");

        jLabelGolesJuga.setText("Goles:");

        jLabelPlusGolJuga.setText("Plus por gol:");

        jTextFieldSueldoJuga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSueldoJugaFocusLost(evt);
            }
        });

        jTextFieldPluspartJuga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPluspartJugaFocusLost(evt);
            }
        });

        jTextFieldGolesJuga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldGolesJugaFocusLost(evt);
            }
        });

        jTextFieldPlusGolJuga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPlusGolJugaFocusLost(evt);
            }
        });

        jLabelPosicionJuga.setText("Posición:");

        buttonGroupPosicion.add(jRadioButtonPortero);
        jRadioButtonPortero.setText("Portero");

        buttonGroupPosicion.add(jRadioButtonDefensa);
        jRadioButtonDefensa.setText("Defensa");

        buttonGroupPosicion.add(jRadioButtonDelantero);
        jRadioButtonDelantero.setText("Delantero");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanelJugadorLayout = new javax.swing.GroupLayout(jPanelJugador);
        jPanelJugador.setLayout(jPanelJugadorLayout);
        jPanelJugadorLayout.setHorizontalGroup(
            jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombre2)
                    .addComponent(jLabelDni2)
                    .addComponent(jLabelDirecc2)
                    .addComponent(jLabelTelef2)
                    .addComponent(jLabelPart2))
                .addGap(18, 18, 18)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombreJuga)
                    .addComponent(jTextFieldPartidosJuga)
                    .addComponent(jTextFieldTelefJuga)
                    .addComponent(jTextFieldDireccJuga)
                    .addComponent(jTextFieldDniJuga, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSueldoJuga)
                    .addComponent(jLabelNacimientoJuga)
                    .addComponent(jLabelPlusPartJuga)
                    .addComponent(jLabelGolesJuga)
                    .addComponent(jLabelPlusGolJuga))
                .addGap(18, 18, 18)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSueldoJuga, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addGroup(jPanelJugadorLayout.createSequentialGroup()
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldPluspartJuga)
                    .addComponent(jTextFieldGolesJuga)
                    .addComponent(jTextFieldPlusGolJuga))
                .addGap(18, 18, 18)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPosicionJuga)
                    .addGroup(jPanelJugadorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDefensa)
                            .addComponent(jRadioButtonPortero)
                            .addComponent(jRadioButtonDelantero))))
                .addGap(19, 19, 19))
        );
        jPanelJugadorLayout.setVerticalGroup(
            jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJugadorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre2)
                    .addComponent(jLabelSueldoJuga)
                    .addComponent(jTextFieldSueldoJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPosicionJuga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDniJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDni2)
                    .addComponent(jLabelNacimientoJuga)
                    .addComponent(jRadioButtonPortero)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDirecc2)
                    .addComponent(jLabelPlusPartJuga)
                    .addComponent(jTextFieldPluspartJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonDefensa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelef2)
                    .addComponent(jLabelGolesJuga)
                    .addComponent(jTextFieldGolesJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonDelantero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPartidosJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPart2)
                    .addComponent(jLabelPlusGolJuga)
                    .addComponent(jTextFieldPlusGolJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jugadores", jPanelJugador);

        jLabelNombre3.setText("Nombre:");

        jTextFieldTelefDirect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefDirectFocusLost(evt);
            }
        });
        jTextFieldTelefDirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefDirectActionPerformed(evt);
            }
        });

        jTextFieldPartidosDirect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPartidosDirectFocusLost(evt);
            }
        });

        jLabelDni3.setText("DNI:");

        jLabelDirecc3.setText("Direción:");

        jLabelTelef3.setText("Teléfono:");

        jLabelPart3.setText("Partidos ganados:");

        jLabelSueldoDirect.setText("Sueldo:");

        jLabelActivoDirect.setText("Activo:");

        jComboBoxActivoDirect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jTextFieldSueldoDirect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSueldoDirectFocusLost(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPresidente);
        jRadioButtonPresidente.setText("Presidente");

        jLabel1.setText("Cargo:");

        buttonGroup1.add(jRadioButtonDelegado);
        jRadioButtonDelegado.setText("Delegado");

        buttonGroup1.add(jRadioButtonSecretario);
        jRadioButtonSecretario.setText("Secretario");

        javax.swing.GroupLayout jPanelDirectivoLayout = new javax.swing.GroupLayout(jPanelDirectivo);
        jPanelDirectivo.setLayout(jPanelDirectivoLayout);
        jPanelDirectivoLayout.setHorizontalGroup(
            jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDirectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombre3)
                    .addComponent(jLabelDni3)
                    .addComponent(jLabelDirecc3)
                    .addComponent(jLabelTelef3)
                    .addComponent(jLabelPart3))
                .addGap(18, 18, 18)
                .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombreDirect)
                    .addComponent(jTextFieldPartidosDirect)
                    .addComponent(jTextFieldTelefDirect)
                    .addComponent(jTextFieldDireccDirect)
                    .addComponent(jTextFieldDniDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDirectivoLayout.createSequentialGroup()
                        .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSueldoDirect)
                            .addComponent(jLabelActivoDirect))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxActivoDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSueldoDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDirectivoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanelDirectivoLayout.createSequentialGroup()
                                .addComponent(jRadioButtonPresidente)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonDelegado)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSecretario)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelDirectivoLayout.setVerticalGroup(
            jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDirectivoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre3)
                    .addComponent(jLabelSueldoDirect)
                    .addComponent(jTextFieldSueldoDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDniDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDni3)
                    .addComponent(jLabelActivoDirect)
                    .addComponent(jComboBoxActivoDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDirectivoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDireccDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDirecc3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelef3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPartidosDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPart3))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanelDirectivoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonPresidente)
                            .addComponent(jRadioButtonDelegado)
                            .addComponent(jRadioButtonSecretario))
                        .addGap(38, 38, 38))))
        );

        jTabbedPane1.addTab("Directivos", jPanelDirectivo);

        jLabelNombre4.setText("Nombre:");

        jTextFieldTelefMant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefMantFocusLost(evt);
            }
        });

        jTextFieldPartidosMant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPartidosMantFocusLost(evt);
            }
        });

        jLabelDni4.setText("DNI:");

        jLabelDirecc4.setText("Direción:");

        jLabelTelef4.setText("Teléfono:");

        jLabelPart4.setText("Partidos ganados:");

        jTextFieldSueldoMant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSueldoMantFocusLost(evt);
            }
        });

        jLabelFijoMant.setText("Fijo");

        jLabelSueldoMant.setText("Sueldo:");

        jComboBoxFijoMant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout jPanelMantenedorLayout = new javax.swing.GroupLayout(jPanelMantenedor);
        jPanelMantenedor.setLayout(jPanelMantenedorLayout);
        jPanelMantenedorLayout.setHorizontalGroup(
            jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMantenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombre4)
                    .addComponent(jLabelDni4)
                    .addComponent(jLabelDirecc4)
                    .addComponent(jLabelTelef4)
                    .addComponent(jLabelPart4))
                .addGap(18, 18, 18)
                .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombreMant)
                    .addComponent(jTextFieldPartidosMant)
                    .addComponent(jTextFieldTelefMant)
                    .addComponent(jTextFieldDireccMant)
                    .addComponent(jTextFieldDniMant, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSueldoMant)
                    .addComponent(jLabelFijoMant))
                .addGap(18, 18, 18)
                .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFijoMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSueldoMant, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanelMantenedorLayout.setVerticalGroup(
            jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMantenedorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMantenedorLayout.createSequentialGroup()
                        .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombreMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDniMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDni4)))
                    .addGroup(jPanelMantenedorLayout.createSequentialGroup()
                        .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSueldoMant)
                            .addComponent(jTextFieldSueldoMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFijoMant)
                            .addComponent(jComboBoxFijoMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDirecc4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelef4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMantenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPartidosMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPart4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mantenedores", jPanelMantenedor);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jMenuArchivo.setText("Archivo");

        jMenuItemAnadir.setText("Añadir");
        jMenuItemAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnadirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAnadir);

        jMenuItemBorrar.setText("Borrar línea");
        jMenuItemBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemBorrar);

        jMenuItemVaciar.setText("Vaciar lista");
        jMenuItemVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVaciarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemVaciar);

        jMenuItemLlenar.setText("Llenar lista");
        jMenuItemLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLlenarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemLlenar);

        jMenuBar1.add(jMenuArchivo);

        jMenuGuarda_Importa.setText("Guardar/Importar");

        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuGuarda_Importa.add(jMenuItemGuardar);

        jMenuItemImportar.setText("Importar");
        jMenuItemImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportarActionPerformed(evt);
            }
        });
        jMenuGuarda_Importa.add(jMenuItemImportar);

        jMenuBar1.add(jMenuGuarda_Importa);

        jMenuOpciones.setText("Opciones");

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSalir.setText("Salir del programa");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        jMenuItemAutor.setText("Autor");
        jMenuItemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutorActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemAutor);

        jMenuItemInstituto.setText("Instituto");
        jMenuItemInstituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInstitutoActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemInstituto);

        jMenuBar1.add(jMenuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelefDirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefDirectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefDirectActionPerformed

    private void jMenuItemAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnadirActionPerformed
        try {
            int selec = jTabbedPane1.getSelectedIndex();
            String nombre, dni, direccion;
            long telefono;
            int partidosGanados;
            
            switch (selec){
                case 0:
                    Entrenadores e = new Entrenadores(Double.parseDouble(jTextFieldSueldoEntre.getText()), Float.parseFloat(jTextFieldPlusEntre.getText()), jTextFieldNombreEntre.getText(), jTextFieldDniEntre.getText(), jTextFieldDireccEntre.getText(), Long.parseLong(jTextFieldTelefEntre.getText()), Integer.parseInt(jTextFieldPartidosEntre.getText()));
                    modelo.addElement(e.toString());
                    break;
                    
                case 1:
                    String posicion ="";
                    if (jRadioButtonDefensa.isSelected()){
                        posicion = "Defensa";
                    } else if (jRadioButtonDelantero.isSelected()){
                        posicion = "Delantero";
                    } else if (jRadioButtonPortero.isSelected()){
                        posicion = "Portero";
                    }
                    
                    double sueldo = Double.parseDouble(jTextFieldSueldoJuga.getText());
                    
                    String fechaNacimiento = sdf.format((Date)jSpinner1.getValue());
                    
                    
                    float plusPartidoGanado = Float.parseFloat(jTextFieldPluspartJuga.getText());
                    int numGoles = Integer.parseInt(jTextFieldGolesJuga.getText());
                    float plusGol = Float.parseFloat(jTextFieldPlusGolJuga.getText());
                    nombre = jTextFieldNombreJuga.getText();
                    dni = jTextFieldDniJuga.getText();
                    direccion = jTextFieldDireccJuga.getText();
                    telefono = Long.parseLong(jTextFieldTelefJuga.getText());
                    partidosGanados = Integer.parseInt(jTextFieldPartidosJuga.getText());
                    
                     
                    
                    Jugadores j = new Jugadores(posicion, sueldo, fechaNacimiento, plusPartidoGanado, numGoles, plusGol, nombre, dni, direccion, telefono, partidosGanados);
                    modelo.addElement(j.toString());
                    break;
                            
                case 2:
                    String cargo ="";
                    if (jRadioButtonPresidente.isSelected()){
                        cargo = "Presidente";
                    } else if (jRadioButtonSecretario.isSelected()){
                        cargo = "Secretario";
                    } else if (jRadioButtonDelegado.isSelected()){
                        cargo = "Delegado";
                    }
                    
                    double sueldoDirect = Double.parseDouble(jTextFieldSueldoDirect.getText());
                    boolean activo;
                    if (jComboBoxActivoDirect.getSelectedIndex() == 0){
                        activo = true;
                    } else {
                        activo = false;
                    }
                    nombre = jTextFieldNombreDirect.getText();
                    dni = jTextFieldDniDirect.getText();
                    direccion = jTextFieldDireccDirect.getText();
                    telefono = Long.parseLong(jTextFieldTelefDirect.getText());
                    partidosGanados = Integer.parseInt(jTextFieldPartidosDirect.getText());
                    
                    Directivos d = new Directivos(cargo, sueldoDirect, activo, nombre, dni, direccion, telefono, partidosGanados);
                    modelo.addElement(d.toString());
                    
                    break;
                    
                case 3:
                    double sueldoMant = Double.parseDouble(jTextFieldSueldoMant.getText());
                    boolean fijo;
                    if (jComboBoxFijoMant.getSelectedIndex() == 0){
                        fijo = true;
                    } else {
                        fijo = false;
                    }
                    nombre = jTextFieldNombreMant.getText();
                    dni = jTextFieldDniMant.getText();
                    direccion = jTextFieldDireccMant.getText();
                    telefono = Long.parseLong(jTextFieldTelefMant.getText());
                    partidosGanados = Integer.parseInt(jTextFieldPartidosMant.getText());
                    
                    Mantenedores m = new Mantenedores(sueldoMant, fijo, nombre, dni, direccion, telefono, partidosGanados);
                    modelo.addElement(m.toString());
                    break;
                    
                    
            }
            
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Ha habido algún error de entrada de datos.");
        } finally {
            limpiarTodo();
        }
    }//GEN-LAST:event_jMenuItemAnadirActionPerformed

    private void jMenuItemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutorActionPerformed
        String mensaje = "Esta aplicación ha sido creada por\nDavid Carro Salinas\nAlumno del Ciclo Superior de \nDesarrollo de Aplicaciones Multiplataforma";
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jMenuItemAutorActionPerformed

    private void jMenuItemInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstitutoActionPerformed
        String mensaje = "I.E.S. Venancio Blanco\nC/Filipinas, 33, 37003\nSalamanca\nwww.iesvenancioblanco.es";
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_jMenuItemInstitutoActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        JFileChooser fc = new JFileChooser();
        
        int i = fc.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            
            File f = fc.getSelectedFile();
            try (FileWriter fw = new FileWriter(f)){
                
                String pasar = "";
                for (int j = 0; j < (int) jList1.getModel().getSize(); j++){
                    pasar += jList1.getModel().getElementAt(j).toString() + "\n";
                }
                
                
                fw.write(pasar);
            } catch (IOException ex) {
                Logger.getLogger(GestionClub.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportarActionPerformed
        JFileChooser fc = new JFileChooser();
        
        int i = fc.showOpenDialog(this);
        
        if (i == JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            try (FileReader lector = new FileReader(f)){
                String cadena ="";
                int valor = lector.read();
                while (valor != -1){
                    cadena += (char)valor;
                    valor = lector.read();
                }
                modelo.addElement(cadena);
                jList1.setModel(modelo);
                lector.close();
            } catch (IOException ex) {
                Logger.getLogger(GestionClub.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemImportarActionPerformed

    private void jMenuItemVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVaciarActionPerformed
        modelo.clear();
        jList1.setModel(modelo);
    }//GEN-LAST:event_jMenuItemVaciarActionPerformed

    private void jMenuItemLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLlenarActionPerformed
        modelo.clear();
        
        
        
        
        
        Entrenadores e = new Entrenadores(1500, 250f, "David Carro", "123456789", "Calle falsa 123", 987654321, 50);
        modelo.addElement(e.toString());
        Jugadores j = new Jugadores("Portero", 1200, "09-02-1992", 100f, 15, 50f, "Benito", "182376123", "Calle no falsa 123", 8716323, 5);
        modelo.addElement(j.toString());
        Directivos d = new Directivos("Presidente", 2000, true,  "Benito dos", "182376123", "Calle no falsa 123", 8716323, 5);
        modelo.addElement(d.toString());
        Mantenedores m = new Mantenedores(700, true, "Benito dos", "182376123", "Calle no falsa 123", 8716323, 5);
         modelo.addElement(m.toString());
         
         
         jList1.setModel(modelo);
    }//GEN-LAST:event_jMenuItemLlenarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        String mensaje = "Gracias por usar esta aplicación, vuelva pronto.";
        JOptionPane.showMessageDialog(this, mensaje);
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jTextFieldTelefMantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefMantFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldTelefMantFocusLost

    private void jTextFieldPartidosMantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPartidosMantFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldPartidosMantFocusLost

    private void jTextFieldSueldoMantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSueldoMantFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldSueldoMantFocusLost

    private void jTextFieldSueldoDirectFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSueldoDirectFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldSueldoDirectFocusLost

    private void jTextFieldTelefDirectFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefDirectFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldTelefDirectFocusLost

    private void jTextFieldPartidosDirectFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPartidosDirectFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldPartidosDirectFocusLost

    private void jTextFieldTelefJugaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefJugaFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldTelefJugaFocusLost

    private void jTextFieldPartidosJugaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPartidosJugaFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldPartidosJugaFocusLost

    private void jTextFieldSueldoJugaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSueldoJugaFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldSueldoJugaFocusLost

    private void jTextFieldPluspartJugaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPluspartJugaFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldPluspartJugaFocusLost

    private void jTextFieldGolesJugaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldGolesJugaFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldGolesJugaFocusLost

    private void jTextFieldPlusGolJugaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlusGolJugaFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldPlusGolJugaFocusLost

    private void jTextFieldTelefEntreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefEntreFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldTelefEntreFocusLost

    private void jTextFieldPartidosEntreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPartidosEntreFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldPartidosEntreFocusLost

    private void jTextFieldSueldoEntreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSueldoEntreFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldSueldoEntreFocusLost

    private void jTextFieldPlusEntreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlusEntreFocusLost
        validarCampoNumerico((JTextField)evt.getComponent());
    }//GEN-LAST:event_jTextFieldPlusEntreFocusLost

    private void jMenuItemBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarActionPerformed
        modelo.remove(jList1.getSelectedIndex());
        jList1.setModel(modelo);
    }//GEN-LAST:event_jMenuItemBorrarActionPerformed

    
    private void validarCampoNumerico(JTextField campo) {
        boolean correcto = true;
        try {
            Double.parseDouble(campo.getText());
            
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error: Debe ingresar un número.", "Error", JOptionPane.ERROR_MESSAGE);
            campo.setText("");
            campo.setBackground(Color.RED);
            campo.requestFocus();
            correcto = false;
        }
        
        if (correcto){
            campo.setBackground(Color.white);
        }
        
    }
    
    public void limpiarTodo(){
    
    
        jTextFieldDireccDirect.setText("");
        jTextFieldDireccEntre.setText("");
        jTextFieldDireccJuga.setText("");
        jTextFieldDireccMant.setText("");
        jTextFieldDniDirect.setText("");
        jTextFieldDniEntre.setText("");
        jTextFieldDniJuga.setText("");
        jTextFieldDniMant.setText("");
        jTextFieldGolesJuga.setText("");
        jTextFieldNombreDirect.setText("");
        jTextFieldNombreEntre.setText("");
        jTextFieldNombreJuga.setText("");
        jTextFieldNombreMant.setText("");
        jTextFieldPartidosDirect.setText("");
        jTextFieldPartidosEntre.setText("");
        jTextFieldPartidosJuga.setText("");
        jTextFieldPartidosMant.setText("");
        jTextFieldPlusEntre.setText("");
        jTextFieldPlusGolJuga.setText("");
        jTextFieldPluspartJuga.setText("");
        jTextFieldSueldoDirect.setText("");
        jTextFieldSueldoEntre.setText("");
        jTextFieldSueldoJuga.setText("");
        jTextFieldSueldoMant.setText("");
        jTextFieldTelefDirect.setText("");
        jTextFieldTelefEntre.setText("");
        jTextFieldTelefJuga.setText("");
        jTextFieldTelefMant.setText("");
        buttonGroup1.clearSelection();
        buttonGroupPosicion.clearSelection();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupPosicion;
    private javax.swing.JComboBox<String> jComboBoxActivoDirect;
    private javax.swing.JComboBox<String> jComboBoxFijoMant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelActivoDirect;
    private javax.swing.JLabel jLabelDirecc1;
    private javax.swing.JLabel jLabelDirecc2;
    private javax.swing.JLabel jLabelDirecc3;
    private javax.swing.JLabel jLabelDirecc4;
    private javax.swing.JLabel jLabelDni1;
    private javax.swing.JLabel jLabelDni2;
    private javax.swing.JLabel jLabelDni3;
    private javax.swing.JLabel jLabelDni4;
    private javax.swing.JLabel jLabelFijoMant;
    private javax.swing.JLabel jLabelGolesJuga;
    private javax.swing.JLabel jLabelNacimientoJuga;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JLabel jLabelNombre4;
    private javax.swing.JLabel jLabelPart1;
    private javax.swing.JLabel jLabelPart2;
    private javax.swing.JLabel jLabelPart3;
    private javax.swing.JLabel jLabelPart4;
    private javax.swing.JLabel jLabelPlusEntre;
    private javax.swing.JLabel jLabelPlusGolJuga;
    private javax.swing.JLabel jLabelPlusPartJuga;
    private javax.swing.JLabel jLabelPosicionJuga;
    private javax.swing.JLabel jLabelSueldoDirect;
    private javax.swing.JLabel jLabelSueldoEntre;
    private javax.swing.JLabel jLabelSueldoJuga;
    private javax.swing.JLabel jLabelSueldoMant;
    private javax.swing.JLabel jLabelTelef1;
    private javax.swing.JLabel jLabelTelef2;
    private javax.swing.JLabel jLabelTelef3;
    private javax.swing.JLabel jLabelTelef4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGuarda_Importa;
    private javax.swing.JMenuItem jMenuItemAnadir;
    private javax.swing.JMenuItem jMenuItemAutor;
    private javax.swing.JMenuItem jMenuItemBorrar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemImportar;
    private javax.swing.JMenuItem jMenuItemInstituto;
    private javax.swing.JMenuItem jMenuItemLlenar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemVaciar;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JPanel jPanelDirectivo;
    private javax.swing.JPanel jPanelEntrenador;
    private javax.swing.JPanel jPanelJugador;
    private javax.swing.JPanel jPanelMantenedor;
    private javax.swing.JRadioButton jRadioButtonDefensa;
    private javax.swing.JRadioButton jRadioButtonDelantero;
    private javax.swing.JRadioButton jRadioButtonDelegado;
    private javax.swing.JRadioButton jRadioButtonPortero;
    private javax.swing.JRadioButton jRadioButtonPresidente;
    private javax.swing.JRadioButton jRadioButtonSecretario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldDireccDirect;
    private javax.swing.JTextField jTextFieldDireccEntre;
    private javax.swing.JTextField jTextFieldDireccJuga;
    private javax.swing.JTextField jTextFieldDireccMant;
    private javax.swing.JTextField jTextFieldDniDirect;
    private javax.swing.JTextField jTextFieldDniEntre;
    private javax.swing.JTextField jTextFieldDniJuga;
    private javax.swing.JTextField jTextFieldDniMant;
    private javax.swing.JTextField jTextFieldGolesJuga;
    private javax.swing.JTextField jTextFieldNombreDirect;
    private javax.swing.JTextField jTextFieldNombreEntre;
    private javax.swing.JTextField jTextFieldNombreJuga;
    private javax.swing.JTextField jTextFieldNombreMant;
    private javax.swing.JTextField jTextFieldPartidosDirect;
    private javax.swing.JTextField jTextFieldPartidosEntre;
    private javax.swing.JTextField jTextFieldPartidosJuga;
    private javax.swing.JTextField jTextFieldPartidosMant;
    private javax.swing.JTextField jTextFieldPlusEntre;
    private javax.swing.JTextField jTextFieldPlusGolJuga;
    private javax.swing.JTextField jTextFieldPluspartJuga;
    private javax.swing.JTextField jTextFieldSueldoDirect;
    private javax.swing.JTextField jTextFieldSueldoEntre;
    private javax.swing.JTextField jTextFieldSueldoJuga;
    private javax.swing.JTextField jTextFieldSueldoMant;
    private javax.swing.JTextField jTextFieldTelefDirect;
    private javax.swing.JTextField jTextFieldTelefEntre;
    private javax.swing.JTextField jTextFieldTelefJuga;
    private javax.swing.JTextField jTextFieldTelefMant;
    // End of variables declaration//GEN-END:variables
}
