--EJ1--
DROP TYPE PERSONA;
DROP TYPE DIRECCION;

CREATE OR REPLACE TYPE DIRECCION AS OBJECT (
    CALLE VARCHAR2(25),
    CIUDAD VARCHAR2(29),
    COD_POSTAL NUMBER(5) );
/
CREATE OR REPLACE TYPE PERSONA AS OBJECT (
    CODIGO NUMBER,
    NOMBRE VARCHAR2(35),
    DIREC DIRECCION,
    FECHA_NAC DATE );
/

---------------------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
  DIR DIRECCION := DIRECCION(NULL, NULL, NULL);
  P PERSONA := PERSONA(NULL, NULL, NULL, NULL);
  DIR2 DIRECCION;
  P2 PERSONA;
BEGIN
  DIR.CALLE := 'Toro, 18';
  DIR.CIUDAD := 'Salamanca';
  DIR.COD_POSTAL := 37002;
  P.CODIGO := 1;
  P.NOMBRE := 'Elisa Gil Ramos';
  P.DIREC := DIR;
  P.FECHA_NAC := TO_DATE('10/10/1980', 'DD/MM/YYYY');

  DBMS_OUTPUT.PUT_LINE('PERSONA 1:');
  DBMS_OUTPUT.PUT_LINE('CODIGO: ' || P.CODIGO);
  DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || P.NOMBRE);
  DBMS_OUTPUT.PUT_LINE('CALLE: ' || P.DIREC.CALLE);
  DBMS_OUTPUT.PUT_LINE('CIUDAD: ' || P.DIREC.CIUDAD);
  DBMS_OUTPUT.PUT_LINE('CODIGO POSTAL: ' || P.DIREC.COD_POSTAL);
  DBMS_OUTPUT.PUT_LINE('FECHA DE NACIMIENTO: ' || TO_CHAR(P.FECHA_NAC, 'DD/MM/YYYY'));

  -- ...

  DIR2 := NEW DIRECCION('C/ Luna 23', 'Sevilla', 64500);
  P2 := NEW PERSONA(2, 'Ana Martín Esteban', DIR2, SYSDATE);

  DBMS_OUTPUT.PUT_LINE('PERSONA 2:');
  DBMS_OUTPUT.PUT_LINE('CODIGO: ' || P2.CODIGO);
  DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || P2.NOMBRE);
  DBMS_OUTPUT.PUT_LINE('CALLE: ' || P2.DIREC.CALLE);
  DBMS_OUTPUT.PUT_LINE('CIUDAD: ' || P2.DIREC.CIUDAD);
  DBMS_OUTPUT.PUT_LINE('CODIGO POSTAL: ' || P2.DIREC.COD_POSTAL);
  DBMS_OUTPUT.PUT_LINE('FECHA DE NACIMIENTO: ' || TO_CHAR(P2.FECHA_NAC, 'DD/MM/YYYY'));
END;
/