--EJ10

DROP TABLE TIPO_DEPARTAMENTO;
DROP TABLE TIPO_EMPLEADO;

CREATE OR REPLACE TYPE TIPO_DEPT AS OBJECT(DNOMBRE VARCHAR2(15), LOC VARCHAR2(15));
CREATE TABLE TIPO_DEPARTAMENTO OF TIPO_DEPT;

CREATE TABLE TIPO_EMPLEADO (
    EMP_NO NUMBER(4),
    APELLIDO VARCHAR(15),
    DEPT REF TIPO_DEPT
);

INSERT INTO TIPO_DEPARTAMENTO SELECT * FROM DEPARTAMENTO;

BEGIN
    FOR EMP IN (SELECT * FROM EMPLEADO) LOOP
        INSERT INTO TIPO_EMPLEADO (EMP_NO, APELLIDO, DEPT) VALUES (EMP.EMP_NO, EMP.APELLIDO, (SELECT REF(D) FROM TIPO_DEPARTAMENTO D WHERE D.DNOMBRE = EMP.DEPT_NOMBRE));
    END LOOP;
END;

SELECT * from TIPO_DEPARTAMENTO;
SELECT EMP_NO, APELLIDO, DEREF(DEPT).DNOMBRE AS DEPT_NOMBRE, DEREF(DEPT).LOC AS DEPT_LOC from TIPO_EMPLEADO;
