-- EJERCICIO 2 --
DROP TYPE ALUMNO;

-- Crear el tipo ALUMNO basado en PERSONA
CREATE OR REPLACE TYPE ALUMNO AS OBJECT (
  INFO_PERSONA PERSONA,
  NOTA_EVALUACION_1 NUMBER,
  NOTA_EVALUACION_2 NUMBER,
  NOTA_EVALUACION_3 NUMBER
);
/
-- Crear un objeto ALUMNO
DECLARE
  ALUMNO_1 ALUMNO;
  ALUMNO_2 ALUMNO;
BEGIN
  -- Inicializar el objeto ALUMNO_1
  ALUMNO_1 := ALUMNO(
    PERSONA(1, 'Juan Perez', DIRECCION('Calle Principal 123', 'Ciudad', 12345), TO_DATE('01/01/1995', 'DD/MM/YYYY')),
    85,
    90,
    78
  );

  -- Inicializar el objeto ALUMNO_2
  ALUMNO_2 := ALUMNO(
    PERSONA(2, 'Ana Rodriguez', DIRECCION('Avenida Secundaria 456', 'Otra Ciudad', 54321), TO_DATE('15/05/1998', 'DD/MM/YYYY')),
    92,
    88,
    95
  );

  -- Mostrar información del ALUMNO_1
  DBMS_OUTPUT.PUT_LINE('ALUMNO 1:');
  DBMS_OUTPUT.PUT_LINE('Código: ' || ALUMNO_1.INFO_PERSONA.CODIGO);
  DBMS_OUTPUT.PUT_LINE('Nombre: ' || ALUMNO_1.INFO_PERSONA.NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Dirección: ' || ALUMNO_1.INFO_PERSONA.DIREC.CALLE || ', ' || ALUMNO_1.INFO_PERSONA.DIREC.CIUDAD || ' ' || ALUMNO_1.INFO_PERSONA.DIREC.COD_POSTAL);
  DBMS_OUTPUT.PUT_LINE('Fecha de Nacimiento: ' || TO_CHAR(ALUMNO_1.INFO_PERSONA.FECHA_NAC, 'DD/MM/YYYY'));
  DBMS_OUTPUT.PUT_LINE('Nota Evaluación 1: ' || ALUMNO_1.NOTA_EVALUACION_1);
  DBMS_OUTPUT.PUT_LINE('Nota Evaluación 2: ' || ALUMNO_1.NOTA_EVALUACION_2);
  DBMS_OUTPUT.PUT_LINE('Nota Evaluación 3: ' || ALUMNO_1.NOTA_EVALUACION_3);

  -- Mostrar información del ALUMNO_2
  DBMS_OUTPUT.PUT_LINE('ALUMNO 2:');
  DBMS_OUTPUT.PUT_LINE('Código: ' || ALUMNO_2.INFO_PERSONA.CODIGO);
  DBMS_OUTPUT.PUT_LINE('Nombre: ' || ALUMNO_2.INFO_PERSONA.NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Dirección: ' || ALUMNO_2.INFO_PERSONA.DIREC.CALLE || ', ' || ALUMNO_2.INFO_PERSONA.DIREC.CIUDAD || ' ' || ALUMNO_2.INFO_PERSONA.DIREC.COD_POSTAL);
  DBMS_OUTPUT.PUT_LINE('Fecha de Nacimiento: ' || TO_CHAR(ALUMNO_2.INFO_PERSONA.FECHA_NAC, 'DD/MM/YYYY'));
  DBMS_OUTPUT.PUT_LINE('Nota Evaluación 1: ' || ALUMNO_2.NOTA_EVALUACION_1);
  DBMS_OUTPUT.PUT_LINE('Nota Evaluación 2: ' || ALUMNO_2.NOTA_EVALUACION_2);
  DBMS_OUTPUT.PUT_LINE('Nota Evaluación 3: ' || ALUMNO_2.NOTA_EVALUACION_3);
END;
/
