--Ejercicio 3 --

DROP TYPE ALUMNO;
DROP TYPE PERSONA;
DROP TYPE DIRECCION;

CREATE OR REPLACE TYPE DIRECCION AS OBJECT (
    CALLE VARCHAR2(25),
    CIUDAD VARCHAR2(29),
    COD_POSTAL NUMBER(5),

    -- Getter y Setter
    MEMBER FUNCTION GET_CALLE RETURN VARCHAR2,
    MEMBER PROCEDURE SET_CALLE(CALLE VARCHAR2),

    MEMBER FUNCTION GET_CIUDAD RETURN VARCHAR2,
    MEMBER PROCEDURE SET_CIUDAD(CIUDAD VARCHAR2),

    MEMBER FUNCTION GET_COD_POSTAL RETURN NUMBER,
    MEMBER PROCEDURE SET_COD_POSTAL(COD_POSTAL NUMBER)
);
/

CREATE OR REPLACE TYPE BODY DIRECCION AS

    -- Getter y Setter
    MEMBER FUNCTION GET_CALLE RETURN VARCHAR2 IS
    BEGIN
        RETURN SELF.CALLE;
    END;

    MEMBER PROCEDURE SET_CALLE(CALLE VARCHAR2) IS
    BEGIN
        SELF.CALLE := CALLE;
    END;

    MEMBER FUNCTION GET_CIUDAD RETURN VARCHAR2 IS
    BEGIN
        RETURN SELF.CIUDAD;
    END;

    MEMBER PROCEDURE SET_CIUDAD(CIUDAD VARCHAR2) IS
    BEGIN
        SELF.CIUDAD := CIUDAD;
    END;

    MEMBER FUNCTION GET_COD_POSTAL RETURN NUMBER IS
    BEGIN
        RETURN SELF.COD_POSTAL;
    END;

    MEMBER PROCEDURE SET_COD_POSTAL(COD_POSTAL NUMBER) IS
    BEGIN
        SELF.COD_POSTAL := COD_POSTAL;
    END;
END;
/


CREATE OR REPLACE TYPE PERSONA AS OBJECT (
    CODIGO NUMBER,
    NOMBRE VARCHAR2(35),
    DIREC DIRECCION,
    FECHA_NAC DATE,

    -- Getter y Setter
    MEMBER FUNCTION GET_CODIGO RETURN NUMBER,
    MEMBER PROCEDURE SET_CODIGO(CODIGO NUMBER),

    MEMBER FUNCTION GET_NOMBRE RETURN VARCHAR2,
    MEMBER PROCEDURE SET_NOMBRE(NOMBRE VARCHAR2),

    MEMBER FUNCTION GET_DIREC RETURN DIRECCION,
    MEMBER PROCEDURE SET_DIREC(DIREC DIRECCION),

    MEMBER FUNCTION GET_FECHA_NAC RETURN DATE,
    MEMBER PROCEDURE SET_FECHA_NAC(FECHA_NAC DATE)
);
/

CREATE OR REPLACE TYPE BODY PERSONA AS

    -- Getter y Setter
    MEMBER FUNCTION GET_CODIGO RETURN NUMBER IS
    BEGIN
        RETURN SELF.CODIGO;
    END;

    MEMBER PROCEDURE SET_CODIGO(CODIGO NUMBER) IS
    BEGIN
        SELF.CODIGO := CODIGO;
    END;

    MEMBER FUNCTION GET_NOMBRE RETURN VARCHAR2 IS
    BEGIN
        RETURN SELF.NOMBRE;
    END;

    MEMBER PROCEDURE SET_NOMBRE(NOMBRE VARCHAR2) IS
    BEGIN
        SELF.NOMBRE := NOMBRE;
    END;

    MEMBER FUNCTION GET_DIREC RETURN DIRECCION IS
    BEGIN
        RETURN SELF.DIREC;
    END;

    MEMBER PROCEDURE SET_DIREC(DIREC DIRECCION) IS
    BEGIN
        SELF.DIREC := DIREC;
    END;

    MEMBER FUNCTION GET_FECHA_NAC RETURN DATE IS
    BEGIN
        RETURN SELF.FECHA_NAC;
    END;

    MEMBER PROCEDURE SET_FECHA_NAC(FECHA_NAC DATE) IS
    BEGIN
        SELF.FECHA_NAC := FECHA_NAC;
    END;
END;
/


CREATE OR REPLACE TYPE ALUMNO AS OBJECT (
    INFO_PERSONA PERSONA,
    NOTA_EVALUACION_1 NUMBER,
    NOTA_EVALUACION_2 NUMBER,
    NOTA_EVALUACION_3 NUMBER,

    -- Getter y Setter
    MEMBER FUNCTION GET_INFO_PERSONA RETURN PERSONA,
    MEMBER PROCEDURE SET_INFO_PERSONA(INFO_PERSONA PERSONA),

    MEMBER FUNCTION GET_NOTA_EVALUACION_1 RETURN NUMBER,
    MEMBER PROCEDURE SET_NOTA_EVALUACION_1(NOTA_EVALUACION_1 NUMBER),

    MEMBER FUNCTION GET_NOTA_EVALUACION_2 RETURN NUMBER,
    MEMBER PROCEDURE SET_NOTA_EVALUACION_2(NOTA_EVALUACION_2 NUMBER),

    MEMBER FUNCTION GET_NOTA_EVALUACION_3 RETURN NUMBER,
    MEMBER PROCEDURE SET_NOTA_EVALUACION_3(NOTA_EVALUACION_3 NUMBER)
);
/

CREATE OR REPLACE TYPE BODY ALUMNO AS

    -- Getter y Setter
    MEMBER FUNCTION GET_INFO_PERSONA RETURN PERSONA IS
    BEGIN
        RETURN SELF.INFO_PERSONA;
    END;

    MEMBER PROCEDURE SET_INFO_PERSONA(INFO_PERSONA PERSONA) IS
    BEGIN
        SELF.INFO_PERSONA := INFO_PERSONA;
    END;

    MEMBER FUNCTION GET_NOTA_EVALUACION_1 RETURN NUMBER IS
    BEGIN
        RETURN SELF.NOTA_EVALUACION_1;
    END;

    MEMBER PROCEDURE SET_NOTA_EVALUACION_1(NOTA_EVALUACION_1 NUMBER) IS
    BEGIN
        SELF.NOTA_EVALUACION_1 := NOTA_EVALUACION_1;
    END;

    MEMBER FUNCTION GET_NOTA_EVALUACION_2 RETURN NUMBER IS
    BEGIN
        RETURN SELF.NOTA_EVALUACION_2;
    END;

    MEMBER PROCEDURE SET_NOTA_EVALUACION_2(NOTA_EVALUACION_2 NUMBER) IS
    BEGIN
        SELF.NOTA_EVALUACION_2 := NOTA_EVALUACION_2;
    END;

    MEMBER FUNCTION GET_NOTA_EVALUACION_3 RETURN NUMBER IS
    BEGIN
        RETURN SELF.NOTA_EVALUACION_3;
    END;

    MEMBER PROCEDURE SET_NOTA_EVALUACION_3(NOTA_EVALUACION_3 NUMBER) IS
    BEGIN
        SELF.NOTA_EVALUACION_3 := NOTA_EVALUACION_3;
    END;
END;
/