--Ejercicio 4

DROP TYPE ALUMNO;

CREATE OR REPLACE TYPE ALUMNO AS OBJECT (
    INFO_PERSONA PERSONA,
    NOTA_EVALUACION_1 NUMBER,
    NOTA_EVALUACION_2 NUMBER,
    NOTA_EVALUACION_3 NUMBER,

    -- Getter y Setter
    MEMBER FUNCTION GET_INFO_PERSONA RETURN PERSONA,
    MEMBER PROCEDURE SET_INFO_PERSONA(INFO_PERSONA PERSONA),

    MEMBER FUNCTION GET_NOTA_EVALUACION_1 RETURN NUMBER,
    MEMBER PROCEDURE SET_NOTA_EVALUACION_1(NOTA_EVALUACION_1 NUMBER),

    MEMBER FUNCTION GET_NOTA_EVALUACION_2 RETURN NUMBER,
    MEMBER PROCEDURE SET_NOTA_EVALUACION_2(NOTA_EVALUACION_2 NUMBER),

    MEMBER FUNCTION GET_NOTA_EVALUACION_3 RETURN NUMBER,
    MEMBER PROCEDURE SET_NOTA_EVALUACION_3(NOTA_EVALUACION_3 NUMBER),

    MEMBER FUNCTION CALCULAR_NOTA_MEDIA RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY ALUMNO AS

    MEMBER FUNCTION CALCULAR_NOTA_MEDIA RETURN NUMBER IS
    BEGIN
        RETURN (NOTA_EVALUACION_1 + NOTA_EVALUACION_2 + NOTA_EVALUACION_3) / 3;
    END;

    -- Getter y Setter
    MEMBER FUNCTION GET_INFO_PERSONA RETURN PERSONA IS
    BEGIN
        RETURN SELF.INFO_PERSONA;
    END;

    MEMBER PROCEDURE SET_INFO_PERSONA(INFO_PERSONA PERSONA) IS
    BEGIN
        SELF.INFO_PERSONA := INFO_PERSONA;
    END;

    MEMBER FUNCTION GET_NOTA_EVALUACION_1 RETURN NUMBER IS
    BEGIN
        RETURN SELF.NOTA_EVALUACION_1;
    END;

    MEMBER PROCEDURE SET_NOTA_EVALUACION_1(NOTA_EVALUACION_1 NUMBER) IS
    BEGIN
        SELF.NOTA_EVALUACION_1 := NOTA_EVALUACION_1;
    END;

    MEMBER FUNCTION GET_NOTA_EVALUACION_2 RETURN NUMBER IS
    BEGIN
        RETURN SELF.NOTA_EVALUACION_2;
    END;

    MEMBER PROCEDURE SET_NOTA_EVALUACION_2(NOTA_EVALUACION_2 NUMBER) IS
    BEGIN
        SELF.NOTA_EVALUACION_2 := NOTA_EVALUACION_2;
    END;

    MEMBER FUNCTION GET_NOTA_EVALUACION_3 RETURN NUMBER IS
    BEGIN
        RETURN SELF.NOTA_EVALUACION_3;
    END;

    MEMBER PROCEDURE SET_NOTA_EVALUACION_3(NOTA_EVALUACION_3 NUMBER) IS
    BEGIN
        SELF.NOTA_EVALUACION_3 := NOTA_EVALUACION_3;
    END;
END;
/