--EJERCICIO 5
DROP TABLE ALUMNOS2; --Si no existía todavía comenta esta línea
CREATE TABLE ALUMNOS2 OF ALUMNO;

DECLARE
    DIRECCION1 DIRECCION; DIRECCION2 DIRECCION; DIRECCION3 DIRECCION; DIRECCION4 DIRECCION; DIRECCION5 DIRECCION;
    PERSONA1 PERSONA; PERSONA2 PERSONA; PERSONA3 PERSONA; PERSONA4 PERSONA; PERSONA5 PERSONA;
    ALUMNO1 ALUMNO; ALUMNO2 ALUMNO; ALUMNO3 ALUMNO; ALUMNO4 ALUMNO; ALUMNO5 ALUMNO;

BEGIN
    DIRECCION1 := NEW DIRECCION('CALLE MAYOR', 'SALAMANCA', 28001);
    DIRECCION2 := NEW DIRECCION('PLAZA ESPAÑA', 'BARCELONA', 08010);
    DIRECCION3 := NEW DIRECCION('AVENIDA PRINCIPAL', 'SALAMANCA', 46001);
    DIRECCION4 := NEW DIRECCION('CALLE ALAMEDA', 'SALAMANCA', 41001);
    DIRECCION5 := NEW DIRECCION('CALLE GRAN VIA', 'MÁLAGA', 29001);

    PERSONA1 := NEW PERSONA(1, 'Laura', DIRECCION1, TO_DATE('05/02/1995', 'DD/MM/YYYY'));
    PERSONA2 := NEW PERSONA(2, 'Diego', DIRECCION2, TO_DATE('17/09/1990', 'DD/MM/YYYY'));
    PERSONA3 := NEW PERSONA(3, 'Elena', DIRECCION3, TO_DATE('10/11/1988', 'DD/MM/YYYY'));
    PERSONA4 := NEW PERSONA(4, 'Javier', DIRECCION4, TO_DATE('23/07/1983', 'DD/MM/YYYY'));
    PERSONA5 := NEW PERSONA(5, 'Marina', DIRECCION5, TO_DATE('12/04/1997', 'DD/MM/YYYY'));

    ALUMNO1 := NEW ALUMNO(PERSONA1, 7, 8, 9);
    ALUMNO2 := NEW ALUMNO(PERSONA2, 6, 7, 8);
    ALUMNO3 := NEW ALUMNO(PERSONA3, 8, 9, 7);
    ALUMNO4 := NEW ALUMNO(PERSONA4, 4, 2, 3);
    ALUMNO5 := NEW ALUMNO(PERSONA5, 9, 9, 8);

    INSERT INTO ALUMNOS2 VALUES(ALUMNO1);
    INSERT INTO ALUMNOS2 VALUES(ALUMNO2);
    INSERT INTO ALUMNOS2 VALUES(ALUMNO3);
    INSERT INTO ALUMNOS2 VALUES(ALUMNO4);
    INSERT INTO ALUMNOS2 VALUES(ALUMNO5);
END;
/

SELECT A.INFO_PERSONA.NOMBRE, A.CALCULAR_NOTA_MEDIA() FROM ALUMNOS2 A;

SELECT A.INFO_PERSONA.NOMBRE, A.CALCULAR_NOTA_MEDIA() FROM ALUMNOS2 A
    WHERE A.INFO_PERSONA.DIREC.CIUDAD = 'SALAMANCA' AND A.CALCULAR_NOTA_MEDIA() > 5;

SELECT A.INFO_PERSONA.NOMBRE, A.CALCULAR_NOTA_MEDIA() FROM ALUMNOS2 A
    ORDER BY A.CALCULAR_NOTA_MEDIA() DESC FETCH FIRST ROW ONLY;

SELECT A.INFO_PERSONA.NOMBRE, GREATEST(A.GET_NOTA_EVALUACION_1(), A.GET_NOTA_EVALUACION_2(), A.GET_NOTA_EVALUACION_3()) AS NOTA
    FROM ALUMNOS2 A ORDER BY NOTA DESC FETCH FIRST ROW ONLY;