--EJ7

DROP TABLE EMPLEADO;
DROP TABLE DEPARTAMENTO;
DROP TABLE GRUPOS;

CREATE OR REPLACE TYPE VARRAY_P AS VARRAY(5) OF PERSONA;

CREATE TABLE GRUPOS(
    NOMBRE VARCHAR2(20),
    INTEGRANTES VARRAY_P,
    CALLE VARCHAR(20),
    CODIGO INTEGER
);

CREATE TABLE DEPARTAMENTO(
    NOMBRE VARCHAR(20) PRIMARY KEY,
    LOCALIDAD VARCHAR(20)
);

CREATE TABLE EMPLEADO(
    EMP_NO INTEGER PRIMARY KEY,
    APELLIDO VARCHAR(20),
    DEPT_NOMBRE VARCHAR(20),
    FOREIGN KEY (DEPT_NOMBRE) REFERENCES DEPARTAMENTO(NOMBRE)
);

INSERT INTO DEPARTAMENTO (NOMBRE, LOCALIDAD) VALUES ('Marketing', 'Los Angeles');
INSERT INTO DEPARTAMENTO (NOMBRE, LOCALIDAD) VALUES ('Contabilidad', 'Houston');
INSERT INTO DEPARTAMENTO (NOMBRE, LOCALIDAD) VALUES ('Logística', 'Miami');
INSERT INTO DEPARTAMENTO (NOMBRE, LOCALIDAD) VALUES ('Finanzas', 'Dallas');
INSERT INTO DEPARTAMENTO (NOMBRE, LOCALIDAD) VALUES ('Producción', 'Seattle');
INSERT INTO DEPARTAMENTO (NOMBRE, LOCALIDAD) VALUES ('Ventas', 'Miami');

INSERT INTO EMPLEADO (EMP_NO, APELLIDO, DEPT_NOMBRE) VALUES (1, 'Brown', 'Marketing');
INSERT INTO EMPLEADO (EMP_NO, APELLIDO, DEPT_NOMBRE) VALUES (2, 'Miller', 'Contabilidad');
INSERT INTO EMPLEADO (EMP_NO, APELLIDO, DEPT_NOMBRE) VALUES (3, 'Wilson', 'Logística');
INSERT INTO EMPLEADO (EMP_NO, APELLIDO, DEPT_NOMBRE) VALUES (4, 'Anderson', 'Finanzas');
INSERT INTO EMPLEADO (EMP_NO, APELLIDO, DEPT_NOMBRE) VALUES (5, 'Thomas', 'Producción');
INSERT INTO EMPLEADO (EMP_NO, APELLIDO, DEPT_NOMBRE) VALUES (6, 'Jackson', 'Ventas');

CREATE OR REPLACE PROCEDURE RELLENAR_GRUPOS AS
    arrayPers VARRAY_P;
    idMax NUMBER;
BEGIN
    FOR DEPT IN (SELECT * FROM DEPARTAMENTO) LOOP
        arrayPers := VARRAY_P();
        FOR EMP IN (SELECT * FROM EMPLEADO WHERE DEPT_NOMBRE = DEPT.NOMBRE) LOOP
            IF arrayPers.COUNT < 5 THEN
                arrayPers.EXTEND;
                DECLARE
                    DIR DIRECCION;
                BEGIN
                    DIR := DIRECCION(DEPT.LOCALIDAD, 'Salamanca', 37003);
                    arrayPers(arrayPers.LAST) := PERSONA(EMP.EMP_NO, EMP.APELLIDO, DIR, '04/01/2003');
                END;

            ELSE
                EXIT;
            END IF;
        END LOOP;

        SELECT MAX(CODIGO) INTO idMax FROM GRUPOS;

        IF idMax IS NULL THEN
            idMax := 1;
        ELSE
            idMax := idMax + 1;
        END IF;

        INSERT INTO GRUPOS VALUES (DEPT.NOMBRE, arrayPers, DEPT.LOCALIDAD, idMax);
    END LOOP;
END;

CALL RELLENAR_GRUPOS();
SELECT * FROM GRUPOS;
