--Ej 8

DROP TABLE EJ_TABLA_ANIDADA;

CREATE OR REPLACE TYPE TABLA_ANIDADA AS TABLE OF DIRECCION;

CREATE TABLE EJ_TABLA_ANIDADA (
    ID NUMBER(2),
    APELLIDOS VARCHAR2(35),
    DIREC TABLA_ANIDADA
)
NESTED TABLE DIREC STORE AS DIREC_ANIDADA;

INSERT INTO EJ_TABLA_ANIDADA VALUES(
    1,
    'GARCÍA',
    TABLA_ANIDADA(
    DIRECCION('Gran Vía 15', 'Salamanca', 08002),
    DIRECCION('Gràcia 22', 'Barcelona', 08007),
    DIRECCION('Carmelos 34', 'Barcelona', 08003))
);

INSERT INTO EJ_TABLA_ANIDADA VALUES(
    2,
    'FERNÁNDEZ',
    TABLA_ANIDADA(
        DIRECCION('Mayor 10', 'Valencia', 46002),
        DIRECCION('Puerto 55', 'Valencia', 46023),
        DIRECCION('Reina 8', 'Valencia', 46001)
    )
);

INSERT INTO EJ_TABLA_ANIDADA VALUES(
    3,
    'RODRÍGUEZ',
    TABLA_ANIDADA(
        DIRECCION('San Francisco 5', 'Sevilla', 41004),
        DIRECCION('Constitución 20', 'Sevilla', 41001)
    )
);

SELECT ID, APELLIDOS, CURSOR(SELECT nestedTab.CALLE, nestedTab.COD_POSTAL FROM TABLE(T.DIREC) nestedTab) AS DIRECCIONES FROM EJ_TABLA_ANIDADA T;

SELECT CALLE FROM THE (SELECT T.DIREC FROM EJ_TABLA_ANIDADA T WHERE ID=1) WHERE CIUDAD='Salamanca';

SELECT * FROM THE (SELECT T.DIREC FROM EJ_TABLA_ANIDADA T WHERE ID=2);

SELECT COUNT(CIUDAD), CIUDAD FROM THE (SELECT T.DIREC FROM EJ_TABLA_ANIDADA T WHERE ID=1) GROUP BY CIUDAD;

SELECT COUNT(CIUDAD), CIUDAD FROM THE (SELECT T.DIREC FROM EJ_TABLA_ANIDADA T WHERE ID=1)GROUP BY CIUDAD ORDER BY COUNT(CIUDAD) DESC FETCH FIRST ROW ONLY;

BEGIN
    FOR SUBTABLA IN (SELECT * FROM EJ_TABLA_ANIDADA) LOOP
        DBMS_OUTPUT.PUT_LINE('APELLIDO: ' || SUBTABLA.APELLIDOS );

        FOR CALLEDETABLA IN (SELECT CALLE FROM THE (SELECT T.DIREC FROM EJ_TABLA_ANIDADA T WHERE T.APELLIDOS = SUBTABLA.APELLIDOS)) LOOP
            DBMS_OUTPUT.PUT_LINE('    CALLE: ' || CALLEDETABLA.CALLE );

        END LOOP;
    END LOOP;
END;


--EJ9
CREATE OR REPLACE PROCEDURE INSERT_DIRECCION (id NUMBER, dir DIRECCION) AS
    idsExist NUMBER;
    tablaDir TABLA_ANIDADA;
    tablaA TABLA_ANIDADA;

BEGIN
    SELECT COUNT(*) INTO idsExist FROM EJ_TABLA_ANIDADA WHERE ID = id;

    IF idsExist = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No existe ' || id);
        RETURN;

    ELSE
        DBMS_OUTPUT.PUT_LINE('Existe ' || id);

    END IF;

    SELECT DIREC INTO tablaDir FROM EJ_TABLA_ANIDADA WHERE ID = id;

    IF tablaDir IS NOT NULL THEN
        INSERT INTO TABLE (SELECT DIREC FROM EJ_TABLA_ANIDADA WHERE ID=id) VALUES (dir);
        DBMS_OUTPUT.PUT_LINE('Dirección actualizada');

    ELSE
        tablaA := new TABLA_ANIDADA();
        UPDATE EJ_TABLA_ANIDADA SET DIREC = tablaA WHERE ID = id;

        INSERT INTO TABLE (SELECT DIREC FROM EJ_TABLA_ANIDADA WHERE ID = id) VALUES (dir);
        DBMS_OUTPUT.PUT_LINE('La dirección en la tabla es null. No se puede actualizar.');

    END IF;
END;
/

