/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectolayouts;

import java.awt.Color;

/**
 *
 * @author 6002755
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAzul = new javax.swing.JButton();
        jButtonRojo = new javax.swing.JButton();
        jButtonVerde = new javax.swing.JButton();
        jButtonNegro = new javax.swing.JButton();
        jButtonBlanco = new javax.swing.JButton();
        jButtonNaranja = new javax.swing.JButton();
        jButtonAmarillo = new javax.swing.JButton();
        jButtonMorado = new javax.swing.JButton();
        jButtonMarron = new javax.swing.JButton();
        jPanelArriba = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAbajo = new javax.swing.JPanel();
        jPanelDerecha = new javax.swing.JPanel();
        jPanelIzquierda = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        jButtonAzul.setText("Azul Ariba Izquierda");
        jButtonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAzulActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAzul);

        jButtonRojo.setText("Rojo Arriba");
        jButtonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRojoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRojo);

        jButtonVerde.setText("Verde Arriba Derecha");
        jButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerdeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVerde);

        jButtonNegro.setText("Negro izquierda");
        jButtonNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNegro);

        jButtonBlanco.setText("Blanco Todos");
        jButtonBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlancoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBlanco);

        jButtonNaranja.setText("Naranja Derecha");
        jButtonNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNaranjaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNaranja);

        jButtonAmarillo.setText("Amarillo Abajo Izquierda");
        jButtonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmarilloActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAmarillo);

        jButtonMorado.setText("Morado Abajo");
        jButtonMorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoradoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMorado);

        jButtonMarron.setText("Marron Abajo Derecha");
        jButtonMarron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarronActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMarron);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanelArriba.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setText("Free layout");

        javax.swing.GroupLayout jPanelArribaLayout = new javax.swing.GroupLayout(jPanelArriba);
        jPanelArriba.setLayout(jPanelArribaLayout);
        jPanelArribaLayout.setHorizontalGroup(
            jPanelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArribaLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(496, Short.MAX_VALUE))
        );
        jPanelArribaLayout.setVerticalGroup(
            jPanelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArribaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelArriba, java.awt.BorderLayout.PAGE_START);

        jPanelAbajo.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanelAbajoLayout = new javax.swing.GroupLayout(jPanelAbajo);
        jPanelAbajo.setLayout(jPanelAbajoLayout);
        jPanelAbajoLayout.setHorizontalGroup(
            jPanelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanelAbajoLayout.setVerticalGroup(
            jPanelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAbajo, java.awt.BorderLayout.PAGE_END);

        jPanelDerecha.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanelDerechaLayout = new javax.swing.GroupLayout(jPanelDerecha);
        jPanelDerecha.setLayout(jPanelDerechaLayout);
        jPanelDerechaLayout.setHorizontalGroup(
            jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelDerechaLayout.setVerticalGroup(
            jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelDerecha, java.awt.BorderLayout.LINE_END);

        jPanelIzquierda.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanelIzquierdaLayout = new javax.swing.GroupLayout(jPanelIzquierda);
        jPanelIzquierda.setLayout(jPanelIzquierdaLayout);
        jPanelIzquierdaLayout.setHorizontalGroup(
            jPanelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelIzquierdaLayout.setVerticalGroup(
            jPanelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelIzquierda, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerdeActionPerformed
        jPanelArriba.setBackground(new Color(46,204,113));
        
        jPanelDerecha.setBackground(new Color(46,204,113));    }//GEN-LAST:event_jButtonVerdeActionPerformed

    private void jButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAzulActionPerformed
        jPanelArriba.setBackground(new Color(41,128,185));
        jPanelIzquierda.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_jButtonAzulActionPerformed

    private void jButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRojoActionPerformed
        jPanelArriba.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jButtonRojoActionPerformed

    private void jButtonNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegroActionPerformed
        
        jPanelIzquierda.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jButtonNegroActionPerformed

    private void jButtonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmarilloActionPerformed
        jPanelAbajo.setBackground(new Color(244,208,63));
        jPanelIzquierda.setBackground(new Color(244,208,63));
    }//GEN-LAST:event_jButtonAmarilloActionPerformed

    private void jButtonMoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoradoActionPerformed
        jPanelAbajo.setBackground(new Color(118,68,138));
    }//GEN-LAST:event_jButtonMoradoActionPerformed

    private void jButtonMarronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarronActionPerformed
        jPanelAbajo.setBackground(new Color(147,81,22));
        jPanelDerecha.setBackground(new Color(147,81,22));
    }//GEN-LAST:event_jButtonMarronActionPerformed

    private void jButtonBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlancoActionPerformed
        jPanelAbajo.setBackground(new Color(255,255,255));
        jPanelDerecha.setBackground(new Color(255,255,255));
        jPanelArriba.setBackground(new Color(255,255,255));
        jPanelIzquierda.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonBlancoActionPerformed

    private void jButtonNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNaranjaActionPerformed
        jPanelDerecha.setBackground(new Color(245,176,65));
    }//GEN-LAST:event_jButtonNaranjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmarillo;
    private javax.swing.JButton jButtonAzul;
    private javax.swing.JButton jButtonBlanco;
    private javax.swing.JButton jButtonMarron;
    private javax.swing.JButton jButtonMorado;
    private javax.swing.JButton jButtonNaranja;
    private javax.swing.JButton jButtonNegro;
    private javax.swing.JButton jButtonRojo;
    private javax.swing.JButton jButtonVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAbajo;
    private javax.swing.JPanel jPanelArriba;
    private javax.swing.JPanel jPanelDerecha;
    private javax.swing.JPanel jPanelIzquierda;
    // End of variables declaration//GEN-END:variables
}
