package clases;
// Generated 26 feb. 2024 16:28:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detallepedidos generated by hbm2java
 */
public class Detallepedidos  implements java.io.Serializable {


     private DetallepedidosId id;
     private Pedidos pedidos;
     private Productos productos;
     private int cantidad;
     private BigDecimal precioUnidad;
     private short numeroLinea;

    public Detallepedidos() {
    }

    public Detallepedidos(DetallepedidosId id, Pedidos pedidos, Productos productos, int cantidad, BigDecimal precioUnidad, short numeroLinea) {
       this.id = id;
       this.pedidos = pedidos;
       this.productos = productos;
       this.cantidad = cantidad;
       this.precioUnidad = precioUnidad;
       this.numeroLinea = numeroLinea;
    }
   
    public DetallepedidosId getId() {
        return this.id;
    }
    
    public void setId(DetallepedidosId id) {
        this.id = id;
    }
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(BigDecimal precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public short getNumeroLinea() {
        return this.numeroLinea;
    }
    
    public void setNumeroLinea(short numeroLinea) {
        this.numeroLinea = numeroLinea;
    }

    @Override
    public String toString() {
        return "Detallepedidos{" + "id=" + id + ", pedidos=" + pedidos + ", productos=" + productos + ", cantidad=" + cantidad + ", precioUnidad=" + precioUnidad + ", numeroLinea=" + numeroLinea + '}';
    }




}


