package clases;
// Generated 26 feb. 2024 16:28:13 by Hibernate Tools 4.3.1



/**
 * DetallepedidosId generated by hbm2java
 */
public class DetallepedidosId  implements java.io.Serializable {


     private int codigoPedido;
     private String codigoProducto;

    public DetallepedidosId() {
    }

    public DetallepedidosId(int codigoPedido, String codigoProducto) {
       this.codigoPedido = codigoPedido;
       this.codigoProducto = codigoProducto;
    }
   
    public int getCodigoPedido() {
        return this.codigoPedido;
    }
    
    public void setCodigoPedido(int codigoPedido) {
        this.codigoPedido = codigoPedido;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallepedidosId) ) return false;
		 DetallepedidosId castOther = ( DetallepedidosId ) other; 
         
		 return (this.getCodigoPedido()==castOther.getCodigoPedido())
 && ( (this.getCodigoProducto()==castOther.getCodigoProducto()) || ( this.getCodigoProducto()!=null && castOther.getCodigoProducto()!=null && this.getCodigoProducto().equals(castOther.getCodigoProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigoPedido();
         result = 37 * result + ( getCodigoProducto() == null ? 0 : this.getCodigoProducto().hashCode() );
         return result;
   }   


}


