package clases;
// Generated 26 feb. 2024 16:28:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int codigoEmpleado;
     private Empleados empleados;
     private Oficinas oficinas;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String extension;
     private String email;
     private String puesto;
     private Set empleadoses = new HashSet(0);
     private Set clienteses = new HashSet(0);

    public Empleados() {
    }

	
    public Empleados(int codigoEmpleado, Oficinas oficinas, String nombre, String apellido1, String extension, String email) {
        this.codigoEmpleado = codigoEmpleado;
        this.oficinas = oficinas;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.extension = extension;
        this.email = email;
    }
    public Empleados(int codigoEmpleado, Empleados empleados, Oficinas oficinas, String nombre, String apellido1, String apellido2, String extension, String email, String puesto, Set empleadoses, Set clienteses) {
       this.codigoEmpleado = codigoEmpleado;
       this.empleados = empleados;
       this.oficinas = oficinas;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.extension = extension;
       this.email = email;
       this.puesto = puesto;
       this.empleadoses = empleadoses;
       this.clienteses = clienteses;
    }
   
    public int getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(int codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Oficinas getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(Oficinas oficinas) {
        this.oficinas = oficinas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


