package clases;
// Generated 26 feb. 2024 16:28:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gamasproductos generated by hbm2java
 */
public class Gamasproductos  implements java.io.Serializable {


     private String gama;
     private String descripcionTexto;
     private String descripcionHtml;
     private byte[] imagen;
     private Set productoses = new HashSet(0);

    public Gamasproductos() {
    }

	
    public Gamasproductos(String gama) {
        this.gama = gama;
    }
    public Gamasproductos(String gama, String descripcionTexto, String descripcionHtml, byte[] imagen, Set productoses) {
       this.gama = gama;
       this.descripcionTexto = descripcionTexto;
       this.descripcionHtml = descripcionHtml;
       this.imagen = imagen;
       this.productoses = productoses;
    }
   
    public String getGama() {
        return this.gama;
    }
    
    public void setGama(String gama) {
        this.gama = gama;
    }
    public String getDescripcionTexto() {
        return this.descripcionTexto;
    }
    
    public void setDescripcionTexto(String descripcionTexto) {
        this.descripcionTexto = descripcionTexto;
    }
    public String getDescripcionHtml() {
        return this.descripcionHtml;
    }
    
    public void setDescripcionHtml(String descripcionHtml) {
        this.descripcionHtml = descripcionHtml;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


