package clases;
// Generated 26 feb. 2024 16:28:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private int codigoPedido;
     private Clientes clientes;
     private Date fechaPedido;
     private Date fechaEsperada;
     private Date fechaEntrega;
     private String estado;
     private String comentarios;
     private Set detallepedidoses = new HashSet(0);

    public Pedidos() {
    }

	
    public Pedidos(int codigoPedido, Clientes clientes, Date fechaPedido, Date fechaEsperada, String estado) {
        this.codigoPedido = codigoPedido;
        this.clientes = clientes;
        this.fechaPedido = fechaPedido;
        this.fechaEsperada = fechaEsperada;
        this.estado = estado;
    }
    public Pedidos(int codigoPedido, Clientes clientes, Date fechaPedido, Date fechaEsperada, Date fechaEntrega, String estado, String comentarios, Set detallepedidoses) {
       this.codigoPedido = codigoPedido;
       this.clientes = clientes;
       this.fechaPedido = fechaPedido;
       this.fechaEsperada = fechaEsperada;
       this.fechaEntrega = fechaEntrega;
       this.estado = estado;
       this.comentarios = comentarios;
       this.detallepedidoses = detallepedidoses;
    }
   
    public int getCodigoPedido() {
        return this.codigoPedido;
    }
    
    public void setCodigoPedido(int codigoPedido) {
        this.codigoPedido = codigoPedido;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Date getFechaEsperada() {
        return this.fechaEsperada;
    }
    
    public void setFechaEsperada(Date fechaEsperada) {
        this.fechaEsperada = fechaEsperada;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Set getDetallepedidoses() {
        return this.detallepedidoses;
    }
    
    public void setDetallepedidoses(Set detallepedidoses) {
        this.detallepedidoses = detallepedidoses;
    }

    @Override
    public String toString() {
        return "Pedidos{" + "codigoPedido=" + codigoPedido + ", fechaPedido=" + fechaPedido + ", fechaEsperada=" + fechaEsperada + ", fechaEntrega=" + fechaEntrega + ", estado=" + estado + ", comentarios=" + comentarios + '}';
    }




}


