package clases;
// Generated 26 feb. 2024 16:28:13 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private String codigoProducto;
     private Gamasproductos gamasproductos;
     private String nombre;
     private String dimensiones;
     private String proveedor;
     private String descripcion;
     private short cantidadEnStock;
     private BigDecimal precioVenta;
     private BigDecimal precioProveedor;
     private Set detallepedidoses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String codigoProducto, Gamasproductos gamasproductos, String nombre, short cantidadEnStock, BigDecimal precioVenta) {
        this.codigoProducto = codigoProducto;
        this.gamasproductos = gamasproductos;
        this.nombre = nombre;
        this.cantidadEnStock = cantidadEnStock;
        this.precioVenta = precioVenta;
    }
    public Productos(String codigoProducto, Gamasproductos gamasproductos, String nombre, String dimensiones, String proveedor, String descripcion, short cantidadEnStock, BigDecimal precioVenta, BigDecimal precioProveedor, Set detallepedidoses) {
       this.codigoProducto = codigoProducto;
       this.gamasproductos = gamasproductos;
       this.nombre = nombre;
       this.dimensiones = dimensiones;
       this.proveedor = proveedor;
       this.descripcion = descripcion;
       this.cantidadEnStock = cantidadEnStock;
       this.precioVenta = precioVenta;
       this.precioProveedor = precioProveedor;
       this.detallepedidoses = detallepedidoses;
    }
   
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public Gamasproductos getGamasproductos() {
        return this.gamasproductos;
    }
    
    public void setGamasproductos(Gamasproductos gamasproductos) {
        this.gamasproductos = gamasproductos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDimensiones() {
        return this.dimensiones;
    }
    
    public void setDimensiones(String dimensiones) {
        this.dimensiones = dimensiones;
    }
    public String getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public short getCantidadEnStock() {
        return this.cantidadEnStock;
    }
    
    public void setCantidadEnStock(short cantidadEnStock) {
        this.cantidadEnStock = cantidadEnStock;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public BigDecimal getPrecioProveedor() {
        return this.precioProveedor;
    }
    
    public void setPrecioProveedor(BigDecimal precioProveedor) {
        this.precioProveedor = precioProveedor;
    }
    public Set getDetallepedidoses() {
        return this.detallepedidoses;
    }
    
    public void setDetallepedidoses(Set detallepedidoses) {
        this.detallepedidoses = detallepedidoses;
    }

    @Override
    public String toString() {
        return "Productos{" + "codigoProducto=" + codigoProducto + ", nombre=" + nombre + ", dimensiones=" + dimensiones + ", proveedor=" + proveedor + ", descripcion=" + descripcion + '}';
    }




}


