
CREATE TYPE TIPO_DEP AS OBJECT (
    DEPT_NO NUMBER(2),
    DNOMBRE VARCHAR2(15),
    LOC VARCHAR2(15)
);
/


CREATE TABLE TABLA_TIPO OF TIPO_DEP;
/

-- Llenar la tabla
INSERT INTO TABLA_TIPO (DEPT_NO, DNOMBRE, LOC)
SELECT ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, LOCALIZACION
FROM DEPARTAMENTOS;
COMMIT;

-- Crear una tabla con ref TIPO_DEP
CREATE TABLE EMPLEADOS_TIPO_DEP (
    EMP_NO NUMBER(4),
    APELLIDO VARCHAR2(50),
    SALARIO NUMBER(6,2),
    DEPT REF TIPO_DEP
);
/

-- Llenar tabla con EMPLEADOS
INSERT INTO EMPLEADOS_TIPO_DEP (EMP_NO, APELLIDO, SALARIO, DEPT)
SELECT ID_EMPLEADO, APELLIDO, SALARIO, REF(T)
FROM EMPLEADOS E
JOIN TABLA_TIPO T ON E.ID_DEPARTAMENTO = T.DEPT_NO;
COMMIT;

-- Crear un bloque PL/SQL 
SET SERVEROUTPUT ON;
DECLARE
BEGIN
    FOR emp_rec IN (SELECT E.APELLIDO, E.SALARIO, DEREF(E.DEPT).DEPT_NO AS DEPT_NO,
                           DEREF(E.DEPT).DNOMBRE AS DNOMBRE, DEREF(E.DEPT).LOC AS LOC
                    FROM EMPLEADOS_TIPO_DEP E)
    LOOP
        DBMS_OUTPUT.PUT_LINE('Apellido: ' || emp_rec.APELLIDO || ', Salario: ' || emp_rec.SALARIO || 
                             ', Número de departamento: ' || emp_rec.DEPT_NO || ', Nombre: ' || 
                             emp_rec.DNOMBRE || ', Localidad: ' || emp_rec.LOC);
    END LOOP;
END;
/