CREATE OR REPLACE TYPE DIRECCION AS OBJECT (
CALLE VARCHAR2(25),
CIUDAD VARCHAR2(29),
COD_POSTAL NUMBER(5),

MEMBER PROCEDURE SET_CALLE(C VARCHAR2),
MEMBER FUNCTION GET_CALLE RETURN VARCHAR2,
MEMBER PROCEDURE SET_CIUDAD(C VARCHAR2),
MEMBER FUNCTION GET_CIUDAD RETURN VARCHAR2,
MEMBER PROCEDURE SET_COD_POSTAL(C NUMBER),
MEMBER FUNCTION GET_COD_POSTAL RETURN NUMBER);
/

CREATE OR REPLACE TYPE BODY DIRECCION AS
    MEMBER PROCEDURE SET_CALLE(C VARCHAR2) IS
    BEGIN
        CALLE := C;
    END SET_CALLE;

    MEMBER FUNCTION GET_CALLE RETURN VARCHAR2 IS
    BEGIN
        RETURN CALLE;
    END GET_CALLE;

    MEMBER PROCEDURE SET_CIUDAD(C VARCHAR2) IS
    BEGIN
        CIUDAD := C;
    END SET_CIUDAD;

    MEMBER FUNCTION GET_CIUDAD RETURN VARCHAR2 IS
    BEGIN
        RETURN CIUDAD;
    END GET_CIUDAD;

    MEMBER PROCEDURE SET_COD_POSTAL(C NUMBER) IS
    BEGIN
        COD_POSTAL := C;
    END SET_COD_POSTAL;

    MEMBER FUNCTION GET_COD_POSTAL RETURN NUMBER IS
    BEGIN
        RETURN COD_POSTAL;
    END GET_COD_POSTAL;
END;
/

CREATE OR REPLACE TYPE PERSONA AS OBJECT (
CODIGO NUMBER,
NOMBRE VARCHAR2(35),
DIREC DIRECCION,
FECHA_NAC DATE ,

MEMBER PROCEDURE SET_CODIGO(C NUMBER),
MEMBER FUNCTION GET_CODIGO RETURN NUMBER,
MEMBER PROCEDURE SET_NOMBRE(C VARCHAR2),
MEMBER FUNCTION GET_NOMBRE RETURN VARCHAR2,
MEMBER PROCEDURE SET_DIREC(C DIRECCION),
MEMBER FUNCTION GET_DIREC RETURN DIRECCION,
MEMBER PROCEDURE SET_FECHA_NAC(C DATE),
MEMBER FUNCTION GET_FECHA_NAC RETURN DATE);

/
CREATE OR REPLACE TYPE BODY PERSONA AS
    MEMBER PROCEDURE SET_CODIGO(C NUMBER) IS
    BEGIN
        CODIGO := C;
    END SET_CODIGO;

    MEMBER FUNCTION GET_CODIGO RETURN NUMBER IS
    BEGIN
        RETURN CODIGO;
    END GET_CODIGO;

    MEMBER PROCEDURE SET_NOMBRE(C VARCHAR2) IS
    BEGIN
        NOMBRE := C;
    END SET_NOMBRE;

    MEMBER FUNCTION GET_NOMBRE RETURN VARCHAR2 IS
    BEGIN
        RETURN NOMBRE;
    END GET_NOMBRE;

    MEMBER PROCEDURE SET_DIREC(C DIRECCION) IS
    BEGIN
        DIREC := C;
    END SET_DIREC;

    MEMBER FUNCTION GET_DIREC RETURN DIRECCION IS
    BEGIN
        RETURN DIREC;
    END GET_DIREC;

    MEMBER PROCEDURE SET_FECHA_NAC(C DATE) IS
    BEGIN
        FECHA_NAC := C;
    END SET_FECHA_NAC;

    MEMBER FUNCTION GET_FECHA_NAC RETURN DATE IS
    BEGIN
        RETURN FECHA_NAC;
    END GET_FECHA_NAC;
END;
/

CREATE OR REPLACE TYPE ALUMNOS AS OBJECT (
COD NUMBER,
PERS PERSONA,
PRIMERA NUMBER(2),
SEGUNDA NUMBER(2),
TERCERA NUMBER(2) ,

MEMBER PROCEDURE SET_COD(C NUMBER),
MEMBER FUNCTION GET_COD RETURN NUMBER,
MEMBER PROCEDURE SET_PERS(C PERSONA),
MEMBER FUNCTION GET_PERS RETURN PERSONA,
MEMBER PROCEDURE SET_PRIMERA(C NUMBER),
MEMBER FUNCTION GET_PRIMERA RETURN NUMBER,
MEMBER PROCEDURE SET_SEGUNDA(C NUMBER),
MEMBER FUNCTION GET_SEGUNDA RETURN NUMBER,
MEMBER PROCEDURE SET_TERCERA(C NUMBER),
MEMBER FUNCTION GET_TERCERA RETURN NUMBER ,
MEMBER FUNCTION GET_MEDIA RETURN NUMBER);

/
CREATE OR REPLACE TYPE BODY ALUMNOS AS

    MEMBER PROCEDURE SET_COD(C NUMBER) IS
    BEGIN
        COD := C;
    END SET_COD;

    MEMBER FUNCTION GET_COD RETURN NUMBER IS
    BEGIN
        RETURN COD;
    END GET_COD;

    MEMBER PROCEDURE SET_PERS(C PERSONA) IS
    BEGIN
        PERS := C;
    END SET_PERS;

    MEMBER FUNCTION GET_PERS RETURN PERSONA IS
    BEGIN
        RETURN PERS;
    END GET_PERS;

    MEMBER PROCEDURE SET_PRIMERA(C NUMBER) IS
    BEGIN
        PRIMERA := C;
    END SET_PRIMERA;

    MEMBER FUNCTION GET_PRIMERA RETURN NUMBER IS
    BEGIN
        RETURN PRIMERA;
    END GET_PRIMERA;

    MEMBER PROCEDURE SET_SEGUNDA(C NUMBER) IS
    BEGIN
        SEGUNDA := C;
    END SET_SEGUNDA;

    MEMBER FUNCTION GET_SEGUNDA RETURN NUMBER IS
    BEGIN
        RETURN SEGUNDA;
    END GET_SEGUNDA;

    MEMBER PROCEDURE SET_TERCERA(C NUMBER) IS
    BEGIN
        TERCERA := C;
    END SET_TERCERA;

    MEMBER FUNCTION GET_TERCERA RETURN NUMBER IS
    BEGIN
        RETURN TERCERA;
    END GET_TERCERA;
    MEMBER FUNCTION GET_MEDIA RETURN NUMBER IS
    BEGIN
        RETURN (PRIMERA + SEGUNDA + TERCERA) / 3;
    END GET_MEDIA;
END;
/