CREATE TABLE ALUMNOS2 OF ALUMNOS ( COD PRIMARY KEY);

DECLARE

    DIR DIRECCION:= DIRECCION('Toro, 18', 'Salamanca',37002);
    PER PERSONA:= PERSONA(1, 'Elisa Gil Ramos', DIR, TO_DATE('10/10/1980', 'DD/MM/YYYY'));
    DIR2 DIRECCION:= DIRECCION('PRUEBA', 'ZAMORA',37002);
    PER2 PERSONA:= PERSONA(2, 'PRUEBA1', DIR2, TO_DATE('10/10/2000', 'DD/MM/YYYY'));
    DIR3 DIRECCION:= DIRECCION('PRUEBA2', 'CACERES',37002);
    PER3 PERSONA:= PERSONA(3, 'PRUEBA2', DIR3, TO_DATE('01/11/1998', 'DD/MM/YYYY'));
    DIR4 DIRECCION:= DIRECCION('PRUEBA3', 'MADRID',37002);
    PER4 PERSONA:= PERSONA(4, 'PRUEBA3', DIR4, TO_DATE('09/12/1993', 'DD/MM/YYYY'));
    AL1 ALUMNOS:= ALUMNOS (1, PER, 5, 6, 7);
    AL2 ALUMNOS:= ALUMNOS (2, PER2, 7, 1, 8);
    AL3 ALUMNOS:= ALUMNOS (3, PER3, 6, 3, 9);
    AL4 ALUMNOS:= ALUMNOS (4, PER4, 9, 9, 9);
BEGIN
    INSERT INTO ALUMNOS2 VALUES(AL1);
    INSERT INTO ALUMNOS2 VALUES(AL2);
    INSERT INTO ALUMNOS2 VALUES(AL3);
    INSERT INTO ALUMNOS2 VALUES(AL4);
    COMMIT;
END;
/

-- Nombre del alumno y su nota media
SELECT A.PERS.NOMBRE , A.GET_MEDIA() AS NOTA_MEDIA FROM ALUMNOS2 A;

-- Alumnos de Salamanca con nota media aprobada.
SELECT A.PERS.NOMBRE, A.GET_MEDIA() AS NOTA_MEDIA 
FROM ALUMNOS2 A 
WHERE A.GET_MEDIA() > 5 AND A.PERS.DIREC.CIUDAD = 'Salamanca';

-- Alumno con más nota media.
SELECT A.PERS.NOMBRE, A.GET_MEDIA() AS NOTA_MEDIA 
FROM ALUMNOS2 A 
ORDER BY A.GET_MEDIA() DESC 
FETCH FIRST ROW ONLY;

-- Alumno con nota más alta en cualquiera de sus notas.
SELECT A.PERS.NOMBRE, GREATEST(A.PRIMERA, A.SEGUNDA, A.TERCERA) AS NOTA_MAS_ALTA
FROM ALUMNOS2 A 
ORDER BY GREATEST(A.PRIMERA, A.SEGUNDA, A.TERCERA) DESC 
FETCH FIRST ROW ONLY;